### ISSUE TITLE
Improving dynamic integration of project specific logic

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#100]
By now we have come across often that we need project-specific code / adaption of behavior, etc. 

So we need to implement the possibility that project specifics can be integrated easily and properly while keeping hard-wired assumptions in apis-core as low as possible

This should be done as properly as possible as it will have lasting impact on the codebase and its wiring with apis-ontology.

related issues:
* https://github.com/acdh-oeaw/apis-core-rdf/issues/101
* https://github.com/acdh-oeaw/apis-ontologies/issues/9
* https://github.com/acdh-oeaw/apis-rdf-devops/issues/3
* https://github.com/acdh-oeaw/apis-core-rdf/issues/22

**Comment by steffres** [comment]
In the JF, we agrred that there are three methods to hook project custom logic into an apis instance:
* As separate Django applications that are added by adding them to the `INSTALLED_APPS` list in the project settings and adapting the urls.py accordingly
* As conditional imports in core (as is done on a few occassions already), where a check is done if a specific module exists in the linked `apis_ontology`, and if it does, import it and use it.
* On some occassions, we can utilize Django logic that allows to override certain components, this can be done for example with Templates.

We agreed to focus on the first apporach as this follows Django practices and seems to be able to separate concerns better than conditional imports do. 

However if Django's flexible logic allows it (the third approach), it surely is less intrusive to core to use that.

Conditional imports that already exists in apis-core, would need to be refactored once the first apporach is proven to be better. Until then, we can leave them in the codebase.

**Comment by b1rger** [comment]
I'll look into how to setup an apis project with having the ontology as a individual app and or project

**Comment by sennierer** [comment]
very generic issue, closing for now
