### ISSUE TITLE
reintegrate map feature

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#101]
The feature of vanillla where a map is loaded in the UI for place entities is needed in a project. And it might be useful in other projects too.

I estimate that adapting the relevant code to the rdf architecture is quite easy. The scope of it is quite isolated after all. 

side-note: come to think of it, could we not also connect with open atlas somehow? After all, they are the main authority on historical map data here so it might make sense to move this use-case to them and we would reference their data somehow? I've never worked with open atlas before, so no idea if that is nonsense or feasible.

**Comment by sennierer** [comment]
already implemented
