### ISSUE TITLE
Capitalize fields without verbose names in "additional columns"?

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1028]
I noticed that fields without a `verbose_name` in the "additional columns" dropdown aren't capitalised whereas the field labels in the search/filter form on the left are (probably because that's the Django default).

For consistency, it would make sense to mimic the Django behaviour and capitalize them. 

In this example, model fields: `name`, `latitude`, `longitude`:

<img src="https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/7f8ece81-bbbb-4643-a760-d75c61dce51c" width="300"> 
<img src="https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/ef2294b5-f927-41c4-9e45-1bf1008990d2" width="300">

**Comment by b1rger** [comment]
Probably using `django.forms.utils.pretty_name` would make sense:

https://github.com/django/django/blob/aa74c4083e047473ac385753e047e075e8f04890/django/forms/utils.py#L13

**Comment by koeaw** [comment]
Just saw this also affects the detail view:

![Screenshot 2024-07-03 at 12-10-57 Wien](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/48659d01-cbf4-4f30-90ed-b7c91105fce6)

**Comment by koeaw** [comment]
> Probably using `django.forms.utils.pretty_name` would make sense:
> 
> https://github.com/django/django/blob/aa74c4083e047473ac385753e047e075e8f04890/django/forms/utils.py#L13

Yeah, looks like that's what's used internally for model fields [without `verbose_name`](https://github.com/django/django/blob/c6d1f98d2685f34e009e0fffdcff4ad275e55879/django/contrib/admin/utils.py#L403-L408) & similar as well as form fields [without `label`](https://github.com/django/django/blob/c6d1f98d2685f34e009e0fffdcff4ad275e55879/django/forms/boundfield.py#L23-L24).
