### ISSUE TITLE
implement bibsonomy button on new ajax forms

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#104]
Adding references to triple and reification forms is not working yet. Buttons are correctly displayed though and python values are correctly injected into the button html element. But no errors are thrown, neither at client nor server.

Probably just a small issue about losing connection to some function call somewhere.

The branch affected by this is https://github.com/acdh-oeaw/apis-core-rdf/tree/reification_and_ajax/apis_core

**Comment by b1rger** [comment]
The branch was never merged, hence closing
