### ISSUE TITLE
Entity update view, relations tables: keep table(s) open following interactions

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#1045]
currently whenever table page is changed the panel is closed, should be opened on default

ETA for clarification:  
Certain interactions with the relations tables trigger a reload, which causes all currently open table accordions to close, which isn't great for UX. After a reload, users have to identify the correct accordion/table again and manually reopen it for viewing/further interactions.

**Comment by sennierer** [comment]
maybe we can just create a new query param `active_panel` the open panel in the url. We close all other panels when you open one.

**Comment by b1rger** [comment]
Which panel?
Which table?
Which page?

**Comment by koeaw** [comment]
@b1rger I updated the subject & issue description

**Comment by sennierer** [comment]
lets stick for the moment (as birger is working on the new relatiosn anyway) with setting the page size of the tables (see https://github.com/acdh-oeaw/apis-instance-oebl-pfp/commit/ddd02af060fcf91508726755133fd39fdbd994ad) to a very high number to show all relations..
