### ISSUE TITLE
Replace ContentType.objects call with calls to caching

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#108]
Often we use `ContentType.objects.get` to get a ContentType instance. This should be replaced globally by using the caching module's function `get_contenttype_of_class` in order to avoid DB hits.

https://github.com/acdh-oeaw/apis-core-rdf/blob/0127e330aeb8fdd8cc8e9bb347106e3b65caad09/apis_core/helper_functions/caching.py#L352

**Comment by b1rger** [comment]
Quoting from the original discussion:
> And while we could attach a method to a model class, I'm sceptical. What's the benefit of it in contrast to using the caching module? I see it rather as redundancy and minor inconsistency.
>
> Calling such a function through a class method does not hide more implementation than calling function itself already imo.

Actually it does. The benefit would be that the implementer doesn't have to think about or know another module. The contenttype of a model class is an attribute of that model and therefore it should be implemented as such and not via a function in an unrelated module. Python has excellent support for object oriented programming paradigms, we are using them all over the place, I think we should do this here too
```
@property
def contenttype:
    return caching.get_entity_class_of_name(type(self).__name__)
```
(or get the same information using `get_contenttype_of_class`

**Comment by steffres** [comment]
It's still redundancy as we would have two places in our codebase doing the same thing. 

Also it can be that the contenttype of a some model class other than rootobject is needed somewhere. There, the dev would either need to call the caching module or reattach such a function to the model class at hand. Also keep in mind, that similiar logic might be implemented in the future that don't relate to contenttype only. If we follow your suggestion and if we want to keep consistency we would need to reattach such functions everywhere.

Generally, I think, awareness of the caching module can be expected from an apis dev. Importing and calling it are neglectable costs.

I do see the gained comfort and abstraction you are suggesting, but I think they are quite little nevertheless and are outweighed by consistency of the single caching module focusing on its jobs. Separation of concerns is higher this way.

But again, I will phase out of APIS soon anyway, so I don't have much stake in this disucssion and unless others don't object, I won't object either to such implementation.
