### ISSUE TITLE
APIS_ENTITIES settings don't follow order – unlike entity_settings in models.py

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#109]
**Describe the bug**
The `list_filter` setting for a given entity (partially) ignores the specified field order when it's supplied in `APIS_ENTITIES` in `server_settings.py` but works as expected when part of a model class's `entity_settings` in `models.py`.

Specifically, some default fields (`name` and two date-related fields, I believe `start_date_written` and `end_date_written`) are always displayed (first) in the left-hand side bar in an entity's list view even when they are not included in `list_filters`.

Curiously, this _only_ happens when `list_filter` is set via `APIS_ENTITIES` in `server_settings.py`. When set via `entity_settings`, the fields either show up last in the web form (when they are not part of the list) or in exactly the place they are expected (in cases where they were included in the list).

**ETA: I'm experiencing the same problem for the `additional_cols` setting!** Which is ignored altogether, i.e. fields in that list aren't available in the "Select additional columns" dropdown at all.

**Additional context**
While I'm aware that the default fields in question are meant to be dropped anyway (as they belong to `TempEntityClass`), this should be investigated because it seems to me it's related to the recent-ish reintegration of `APIS_ENTITIES`.

I.e. I'm guessing not all previous refactorings that got rid of `APIS_ENTITIES` in favour of `entity_settings` might have got corrected back fully.

**Comment by koeaw** [comment]
cc @b1rger

**Comment by koeaw** [comment]
Thx for fixing the sorting with that PR!

> But even with that fix, there is (...) which basically adds a bunch of default filters to the end of the list of filters. Not sure what the reasoning here was... Maybe we should simply remove that for loop?

I can't figure out what's getting added there.

Does this add filters to the fields every entity currently (still) inherits from `TempEntityClass`? See [this django-filter docs section](https://django-filter.readthedocs.io/en/stable/ref/filterset.html#automatic-filter-generation-with-model). In which case it sounds useful (in theory; if I'm understanding correctly, the idea is to have sibling child classes inherit filters for the fields they inherit from their shared parent). Though I don't know how we'd use it once `TempEntityClass` is gone...

**Comment by b1rger** [comment]
> I can't figure out what's getting added there.

> Does this add filters to the fields every entity currently (still) inherits from TempEntityClass?

yes, that seems to be the case. you can define your own fields + filters, they will be the first filters in the form. After that it adds all the fields + filters that are not yet part of the filterlist. For the child classes, this function https://github.com/acdh-oeaw/apis-core-rdf/blob/91464d00b98dfbbe123e5cfefba07790096a5255/apis_core/apis_entities/filters.py#L414 should do the trick.

**Comment by koeaw** [comment]
@b1rger I guess this can be closed now? The original issue was solved by PR #44, which you linked in an earlier comment, the later discussion refers to code that was refactored in #145.

**Comment by b1rger** [comment]
> @b1rger I guess this can be closed now?

sure!
