### ISSUE TITLE
Filtering by "related entity contains" returns more/different objects than expected

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1092]
Filtering by "Related Property" and "Related entity contains" doesn't seem to work 100%.

Example:
Filtering Frischmuth `Works` [by related property `WorkType` containing "Artikel"](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/?columns=id&columns=progress_status&columns=title&columns=siglum&custom_search=&search=&progress_status=&title=&subtitle=&siglum=&summary=&text_analysis=&context=&historical_events=&data_source=&related_entity=Artikel&related_property=6&changed_since=&submit=Submit) returns 11 objects; the "Artikel" `WorkType`, however, is [only linked to 5](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.worktype/19336) works.

It seems to me the remaining non-Artikel works are themselves linked to entirely different entity objects _which contain the word_ "Artikel" (i.e. the relationship chain is traversed in different directions on the next level, or possibly on all levels). E.g.:
* [Die Klosterschule](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/25509) of `WorkType` "Übersetzung" is linked to a `PhysicalObject` with ["Zeitungsartikel"](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.physicalobject/25513) in its description
* another Übersetzung ["Spiró, György: Die Hühnerköpfe"](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/20438) also has Vorlassobjekte which contain the word (e.g. [Lexikonartikel](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.physicalobject/20442), [Zeitungsartikel](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.physicalobject/20443))

**Comment by koeaw** [comment]
I'll add there are [two `WorkTypes` which contain the word "Artikel"](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.worktype/?columns=id&columns=progress_status&columns=name&columns=description&custom_search=artikel&search=&progress_status=&name=&alternative_name=&description=&name_plural=&string_identifier=&icon_id=&data_source=&related_entity=&related_property=&changed_since=&submit=Submit) but "Journalartikel" is currently not connected to any `Works` at all. The six additional work objects returned by the filter are of completely different types.

**Comment by b1rger** [comment]
> Filtering Frischmuth `Works` [by related property `WorkType` containing "Artikel"](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/?columns=id&columns=progress_status&columns=title&columns=siglum&custom_search=&search=&progress_status=&title=&subtitle=&siglum=&summary=&text_analysis=&context=&historical_events=&data_source=&related_entity=Artikel&related_property=6&changed_since=&submit=Submit) returns 11 objects; the "Artikel" `WorkType`, however, is [only linked to 5](https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.worktype/19336) works.

The filtering means: give me entities that are related to entities that have "Artikel" in their name and that are somehow connected to a WorkType via `has type | werktyp`. It does *not* filter for entities that are related to werktyps with "Artikel" in their name. The two filters are combined with && but they are independent

**Comment by koeaw** [comment]
> The two filters are combined with && but they are independent

Ohhhhh. Yeah, I was about to follow up with the question if "related entity contains" ignores whatever is selected in "related property" after testing this with a word that only appears in `PhysicalObjects`.

I thought the two worked in conjunction with each other. D'oh.

**Comment by koeaw** [comment]
Hmm, seeing as the rest of the filters are stacked/combined, I'd argue these two should follow the same pattern.

**Comment by b1rger** [comment]
> Hmm, seeing as the rest of the filters are stacked/combined, I'd argue these two should follow the same pattern.

They are combined with all the other filters with &&.

**Comment by koeaw** [comment]
> > Hmm, seeing as the rest of the filters are stacked/combined, I'd argue these two should follow the same pattern.
> 
> They are combined with all the other filters with &&.

Yeah, but I was/am thinking of the relationship filters as stacked (on top of one another), much like the field filters for the entity itself stack.

Perhaps it would help to imagine the two fields flipped, because that's actually how I was thinking of them in my head (i.e. I thought they were arranged weirdly). First I filter by "related property" type, then I restrict _that_ further by adding a search term on top.

Idk, this seems much more logical to me than to simultaneously filter for objects connected via a specific property and for words in objects connected via random (other) properties. But maybe let's discuss this further in person.
