### ISSUE TITLE
Identify collections by name

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#1102]
Currently, all the templatetags that refer to collections take the id of the collection as argument. This is cumbersome to work with and sometimes ids can change. It would be better, if it was possible to pass the name of the collection. But the name is not distinct. We could make it distinct. Another option would be to use the name + the parent as distinct feature and identify the collection by its full path (i.e. `mytags.myentitytags.foo`)

**Comment by sennierer** [comment]
The latter would be definitely the nicer, but the parent could have a parent...so if we opt for the latter we would need the full path and additionally add a validation logic that sets the full path unique.

**Comment by b1rger** [comment]
> a validation logic that sets the full path unique

I guess if we define in the model that `parent + label` have to be unique, that leads to a unique full path, right?
