### ISSUE TITLE
URLs to filtered list views include superfluous fields/columns

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1134]
Fields that aren't actively being filtered on are included (as empty) in the querystring along with ones that _are_ being filtered on. Same for a table's default columns. Additionally, `&submit=Submit` gets added to the end.

Can we leave the unnecessary stuff off? At least the empty fields and the `submit` bit (not sure how feasable it is to track the default columns).

Frischmuth examples:

Default URL to `Works` list view:
https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/

... changes into this when filtered by "Changed by":
https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/?columns=id&columns=progress_status&columns=siglum&custom_search=&search=&progress_status=&title=&subtitle=&siglum=&summary=&text_analysis=&context=&historical_events=&data_source=&related_entity=&related_property=&changed_since=2024-07-01&submit=Submit

The same could be achieved by this (the above minus empty fields and `submit`):
https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/?columns=id&columns=progress_status&columns=siglum&changed_since=2024-07-01

Or this (only the active filter is included in the URL):
https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.work/?changed_since=2024-07-01

**Comment by b1rger** [comment]
I think that is a behavior of django-filters
