### ISSUE TITLE
Drop `apis_metainfo.views.UriGetOrCreate`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#1135]
The idea of the `UriGetOrCreate` view was to be able to simply pass an URI to the view and it either returns the existing model instance with that URI attached to it, or it creates a new model instance. But IIRC we discussed later, that it is actually not possible to deduce from the URI, what kind of object to create (this is why there are different import routes for different model - and *they* do exactly that: create a model instance or return the one that already exists).

So I propose to drop the `UriGetOrCreate` view

**Comment by sennierer** [comment]
lets drop that view in favour of the entity specific import routes
