### ISSUE TITLE
Re-enable full ORM passthrough on auto-generated Serializers

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#115]
The REST API serailizers created by the [Serializer factory](https://github.com/acdh-oeaw/apis-core-rdf/blob/4b0682ea9252898e0b359d2b6a21d1698df0712e/apis_core/api_routers.py#L221) don't take arbitrary Django ORM via their REST API endpoints. They can be added and [imported via settings](https://github.com/acdh-oeaw/apis-core-rdf/blob/4b0682ea9252898e0b359d2b6a21d1698df0712e/apis_core/api_routers.py#L485), but that's a manual and explicit workflow for which we don't see much reason anymore. 

It would be better to enable passing arbitrary ORM params for increased flexibilty. This is already possible in the [additional serializers](https://github.com/acdh-oeaw/apis-core-rdf/blob/4b0682ea9252898e0b359d2b6a21d1698df0712e/apis_core/api_routers.py#L614) so a first approach would be to compare why it's working there and not in the main serializers.

E.g.
what does not work:
https://apis-jelinek.acdh-dev.oeaw.ac.at/apis/api/relations/triple/?subj__name=Yasmin

what works:
https://apis-jelinek.acdh-dev.oeaw.ac.at/apis/api/additional/nested_triples_to_work/?subj__name=Yasmin
with this [serializer definition here](https://github.com/acdh-oeaw/apis-ontologies/blob/d6f3a313499c965a0959f5463cd72ccb2f32b513/jelinek/additional_serializers.py#L572)

**Comment by sennierer** [comment]
its now possible to easily add custom filter classes, closing for now
