### ISSUE TITLE
RDFParser class not working anymore

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#118]
RDFParser class is needed for importing metadata from external reference resources and create new instances from these metadata.

**Comment by b1rger** [comment]
Maybe when fixing this, we could get rid of the `YAML` dependency. If I remember correctly, `RDFParser` is the only module depending on YAML and it is only used for reading a configuration file that could just as well be json or something else from the standard library

**Comment by sennierer** [comment]
Pyyaml does not have any external dependencies, is used in 700k+ projects etc. So its a very stable, rather simple library. I dont think we should get rid of it just because its a dependency. We could decided though that all the configuration in APIS should be done in a similar way. However, I would prefer yaml over json for configuration purposes for its readability and wide adoption (especially for configuration).

**Comment by b1rger** [comment]
It would be great if there was some kind of textual description of what the `RDFParser` should be doing and some test input data. I guess if we fix the parser, we should probably add a method to `RootObject` (`fromrdf`?) that can be inherited and extended by child classes?

**Comment by b1rger** [comment]
This was fixed in 83ce845c73b391f58aadf84033eb396b527d4069 ff.
