### ISSUE TITLE
Allow overriding signal for load data

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1208]
It should be possible to disable post save signals for extracting data into, for example date fields when importing data 

Related to #984

**Comment by b1rger** [comment]
There are two `post_save` signals in apis core:

https://github.com/acdh-oeaw/apis-core-rdf/blob/e09bc43257a44156686754523f47c4448c0464fd/apis_core/apis_entities/models.py#L150

and 

https://github.com/acdh-oeaw/apis-core-rdf/blob/e09bc43257a44156686754523f47c4448c0464fd/apis_core/collections/signals.py#L12

The former can be disabled by setting the `.skip_default_uri` attribute on the instance that is being created to `True` or by setting the `CREATE_DEFAULT_URI` setting to `False`.
The latter only every does anything if used in a session that has collection ids in the `session_collections` variable.

I'd say thats what the issue requests?

**Comment by b1rger** [comment]
> Sort of. LegacyDateMixin for example overrides the save method which I want to skip when I am importing data (or is this not a reasonable expectation?). I am not sure, honestly....

Ah, oke, so its about the `save()` method, not a signal. Definitly a reasonoable expectation to be able to disable that behaviour. We can simply add a check in the `LegacyDateMixin.save()` method, similar to what we do in the `create_default_uri` signal

**Comment by b1rger** [comment]
> Or maybe it's better to have a single flag for loaddata in settings that does nothing beyond importing the data - no signals and no preprocessing in save methods?

I don't understand `a flag for loaddata ... that does nothing beyond importing the data`?
