### ISSUE TITLE
Unused templates, blocks

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1259]
Going through the remaining `style` attributes as per #1258, I'm wondering if the following are still needed:

* [relations_detail_generic.html](https://github.com/acdh-oeaw/apis-core-rdf/blob/ba7ad4c2b450e83069b960d012ff4e3f544306e8/apis_core/apis_relations/templates/apis_relations/relations_detail_generic.html)
* the [modal block](https://github.com/acdh-oeaw/apis-core-rdf/blob/ba7ad4c2b450e83069b960d012ff4e3f544306e8/apis_core/core/templates/base.html#L255-L266) in the main base.html file

The relations template looks like [it belonged with](https://github.com/acdh-oeaw/apis-core-rdf/commit/e1e2e1ec993540b1f7fcb4191feb20e73e0d83e2#diff-dd6109908e571e65ccea1a4a713df1991e2cb4935d0a3fe1d435f4223509a5caL57-L63)  `GenericRelationView`, which was removed in e1e2e1ec993540b1f7fcb4191feb20e73e0d83e2.

The modal block doesn't seem to get used by anything – I guess it's from when we used [a modal to confirm deletion](https://github.com/acdh-oeaw/apis-core-rdf/blob/ba7ad4c2b450e83069b960d012ff4e3f544306e8/apis_core/generic/templates/generic/generic_confirm_delete.html) of an object? For which we're [now using htmx](https://github.com/acdh-oeaw/apis-core-rdf/blob/ba7ad4c2b450e83069b960d012ff4e3f544306e8/apis_core/generic/templates/columns/delete.html), though I don't know if we're intending to keep that or eventually go back to the Bootstrap modal (which is a different discussion to be had). If the modal isn't needed anymore, the custom styling, whose purpose is unclear to me, doesn't need moving, either. ETA: If we wanna keep it, the customisations should be testable somehow.

**Comment by b1rger** [comment]
> The modal block doesn't seem to get used by anything – I guess it's from when we used [a modal to confirm deletion](https://github.com/acdh-oeaw/apis-core-rdf/blob/ba7ad4c2b450e83069b960d012ff4e3f544306e8/apis_core/generic/templates/generic/generic_confirm_delete.html) of an object?

The modal was introduced so it can be used by plugins or projects. The bibsonomy plugin uses it for its form. It was also initially used for the new relations, but this was now replaced by a `dialog` element in a2e80fad3fcfc2903067a072de13af4d0406b6e6.
Once the bibsonomy plugin also moves to a `dialog` element, the modal can be removed.

**Comment by koeaw** [comment]
> > The modal block doesn't seem to get used by anything – I guess it's from when we used [a modal to confirm deletion](https://github.com/acdh-oeaw/apis-core-rdf/blob/ba7ad4c2b450e83069b960d012ff4e3f544306e8/apis_core/generic/templates/generic/generic_confirm_delete.html) of an object?
> 
> The modal was introduced so it can be used by plugins or projects. The bibsonomy plugin uses it for its form. It was also initially used for the new relations, but this was now replaced by a `dialog` element in [a2e80fa](https://github.com/acdh-oeaw/apis-core-rdf/commit/a2e80fad3fcfc2903067a072de13af4d0406b6e6). Once the bibsonomy plugin also moves to a `dialog` element, the modal can be removed.

Ok, thanks. I don't dislike the idea of including a block for a modal – or other "convenience" blocks for projects – in general. This probably more highlights a problem with code that isn't actively used in Core itself but meant to be used downstream. Other bibsonomy-related if-else blocks in templates come to mind. I think it'd be a good idea if there were a way to test this sort of stuff.

I'll move the custom styling as-is for now.

**Comment by b1rger** [comment]
> Ok, thanks. I don't dislike the idea of including a block for a modal – or other "convenience" blocks for projects – in general. This probably more highlights a problem with code that isn't actively used in Core itself

Sorry, I think my comment was more confusing than helpful. The modal was *also* meant for plugins and downstream projects, but it was *also* used in core. The bootstrap modal is an element that is not that easy to inject into the DOM, so it made sense at the time to include it by default. Now that there is the `dialog` element which is more standardized there is no need for the modal anymore. I think our templates should be generic enough to make convenience blocks for projects unneccessary.

> Other bibsonomy-related if-else blocks in templates come to mind.

If such blocks are still present I would consider this to be a bug. We tried hard in the last year to get rid of those

**Comment by koeaw** [comment]
> I think our templates should be generic enough to make convenience blocks for projects unneccessary.

:+1: 

> > Other bibsonomy-related if-else blocks in templates come to mind.
> 
> If such blocks are still present I would consider this to be a bug. We tried hard in the last year to get rid of those

Ah! I came across a couple again while looking to move the last bits of JavaScript out of templates. But that template code is a(n inherited) mess in general, i.e. not representative, and I didn't look elsewhere, just saw them there (where they are nonsensical anyway because they reference code that doesn't exist anymore).
