### ISSUE TITLE
Change package name to `apis-core-rdf`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#1281]
Given that #203 does not to be resolved any time soon, I propose to at least rename the package to `apis-core-rdf` instead of `apis-core`. This way we can use pypi without hijacking the `apis-core` pypi package and we can start publishing packages again.

Projects would then have to change the dependency definition from `apis-core` to `apis-core-rdf`

**Comment by sennierer** [comment]
discussed in jfx and approved to change
