### ISSUE TITLE
Merge Entities form - location

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1285]
At the moment the Merge Entities form in the Edit Entity page appears below the relations table.

Could we have the Merge form along with the entity details on the left panel on the edit view - considering that a successful merge will update the entity fields rather than create relations?

Merge is currently a link in the Actions menu but broken in release 28. Instead of fixing #1278 we could remove the link from this menu and leave the Merge field in a more prominent position.

**Comment by b1rger** [comment]
> considering that a successful merge will update the entity fields rather than create relations?

It should do both (and did for the old relations). But this has to be implemented, see  #1251

**Comment by sennierer** [comment]
following https://github.com/acdh-oeaw/apis-core-rdf/pull/1283
we remove the not needed merge with form from the entities edit view
