### ISSUE TITLE
Optimize by reducing DB hits in favor of caching

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#13]
Like here: https://github.com/acdh-oeaw/apis-core-rdf/blob/77b1ce33f2a677fc9a67e8a2debe59b3311f5ba4/apis_core/apis_metainfo/models.py#L342

**Comment by steffres** [comment]
We have now a dedicated caching module (https://github.com/acdh-oeaw/apis-core-rdf/issues/60). So all work in this regard should utilize / extend that module.

**Comment by sennierer** [comment]
all the links stemming from templates (examples in the template), closing therefore
