### ISSUE TITLE
Relation-oriented (not Entity-oriented) form

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-core-rdf#130]
**ManMax use case**
The ManMax project's data model is explicity factoid-based, with concrete entities (`Person`, `Place`, `Organisation`) and statements derived from sources (`Birth`, `Death`, `Payment`, `ParentChildRelation`, `PerformanceOfMusicalPiece`, `CreationOfArtwork`... there are a lot of statement types). The current design of the relationships form prioritises the related-to entity type over the relationship type (i.e. from a `Birth` statement, there is the accordion panel `Persons`, under which there is a "property type" autocomplete and the person autocomplete).

We would also like to add a "Identification Type" reification ("Explicit in source", "Implicit in Source", "Total Guess", etc.) to each relationship, which makes the form even less obvious to users.

**General use case**
This may be useful for other projects as well. Especially when dealing with more abstract entities (statements, etc.), there will be a few, well-constrained number of ways for entities to relate to each other. It seems more natural (to me at least), to think, in RDF-style:

1. What's the subject (answer: the current page)?
2. What's the predicate?
3. What's the object?

Whereas currently, the logic runs:

1. What's the subject (answer: the current page)?
2. What _type_ of object is it related to?
3. What predicate can connect these two things?
4. What is the _actual_ object?

(i.e. starting at either end and trying to fill out the middle)

**Describe the solution you'd like**
Ideally, the form should:

- For each entity, get all the properties for which it is subject or object
- In the right panel, list the _properties_ as accordion panels (or not as accordion panels: just visible by default) 
- with the reification fields also visible
- and _not_ with the current entity type as a possibility

**Describe alternatives you've considered**
This seems like it might disrupt a lot of current workflows, so perhaps overriding the form for ManMax might be a possibility. Or creating both this new form and keeping the old form in APIS-Core and changing via some settings option.

**Additional context**
A mockup of what I'm thinking of

![Screenshot 2023-04-12 at 11 39 00](https://user-images.githubusercontent.com/77681667/231446941-064a9531-ad69-4a99-8e7a-9e594f066f5d.png)

**Comment by b1rger** [comment]
Not sure what to do with this, so adding the `needs-attention` label. Do we want this in core? Should be easier now, that we have the new relations. If we want that in core, who will implement it?

**Comment by sennierer** [comment]
Richard created a Factoid builder to create factoids on top of APIS. we might create an app for that, but closing this issue for now.
