### ISSUE TITLE
Docs: remove references to apis_ontology

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1330]
There are some leftover [references](https://github.com/search?q=repo%3Aacdh-oeaw%2Fapis-core-rdf%20apis_ontology&type=code) to `apis_ontology` in the code base, which can be confusing for anyone unaware of the previous requirement to name their app that, so should best get removed/replaced with something else where possible.

(I actually thought it was still a requirement, but I'd probably already added [apis-acdhch-default-settings](https://github.com/acdh-oeaw/apis-acdhch-default-settings) as project dependency by that point.)

**Comment by b1rger** [comment]
which term would you prefer instead of `apis_ontology`?

**Comment by b1rger** [comment]
Fixed in f8bb51499fe1da61d925a46db5698a09fa3d7ba8 and 06a960eb83b2b6bc69315f25928e72cf58a545cd
