### ISSUE TITLE
Accessibility issues with links/icons in footer

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1343]
The `title` attributes on the icon links in the footer should get removed/replaced with `alt` attributes on the images.

That aside, I'm experiencing weird behaviour when hovering the icons: the link destinations aren't shown consistently. In FF (ESR), I thought they randomly disappeared, then realised they flip between the bottom left corner of the browser (default) and the bottom right. In Chrome, they drop "under" the visible browser window. Additionally, the space between the icons seems to get underlined on hover (like text would by default).

A cursory inspection revealed the links themselves aren't the same size as the icons they surround; I'm assuming this contributes to or is the source of the issue.

**Comment by b1rger** [comment]
> The `link` attributes for the icon destinations in the footer should get removed/replaced with `alt` attributes on the images.

Can you post an example? I don't know what you are referring to

**Comment by koeaw** [comment]
> Can you post an example? I don't know what you are referring to

Sorry, meant to say `title` attributes! Updated the issue description.

**Comment by b1rger** [comment]
Oke, could you explain why it is preferable to have `alt` attributes instead of `title` attributes?

**Comment by koeaw** [comment]
> Oke, could you explain why it is preferable to have `alt` attributes instead of `title` attributes?


The [HTML specs on `title`](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute):

> Relying on the `title` attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g., requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).

The [HTML specs on `alt` in the context of links containing nothing but an image](https://html.spec.whatwg.org/multipage/images.html#a-link-or-button-containing-nothing-but-the-image): 

> When an `a` element that creates a hyperlink, or a `button` element, has no textual content but contains one or more images, the `alt` attributes must contain text that together convey the purpose of the link or button.

Useful resources which link to more useful resources:
https://www.a11yproject.com/posts/title-attributes/ 
https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html

**Comment by b1rger** [comment]
The one issue was fixed in cfa9006472d59ad8e544173b85cb2bf7d28a2ffa, the other in c2c5594cc73dd61eb5b6a42aa402c2c3d98bec6b
