### ISSUE TITLE
question(relations): custom form field order for subj/obj fields

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1355]
What value should I give in the `field_order` if I want to position the field that appears under the label "Obj" or "Subj"  at the top (or anywhere in particular) in the form? It currently appears at the bottom. I am able to add other field names to `field_order` and change the order of their appearance but not the subject/objetc fields. 

_Subj_ example:
![image](https://github.com/user-attachments/assets/b577af6a-be18-46d3-9ec6-09a3b3bcf33a)

_Obj_ field example:
![image](https://github.com/user-attachments/assets/26a43b91-c018-40e5-96c8-a2e21d533ca0)

**Comment by b1rger** [comment]
> You can try to create a custom `__init__()` and (re)add this line:

actually we could probably do this in our custom relations form
