### ISSUE TITLE
question(relations): should there be a create option in the subj/obj autocomplete?

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1364]
The autocomplete offers a Create option when the input in the autocomplete field does not yield any matching results.
 
I think it should not be possible (and functionally at the moment, it is not possible) to create a new entity in the Subj/Obj field at the time of creating or editing a relation (this is up for debate).

But if we decide to offer this feature then it should work (related to #1363).

**Comment by b1rger** [comment]
We use this feature in a project. The users paste links to rdf data from other sources and create those entities while creating realtions.
Can you explain what happens when you use the `Create` option and what you would expect to happen?

**Comment by b1rger** [comment]
> Oh that's cool! I guess you have handlers to import the RDF into the entity. In case it is not possible to create the entity in the background (if the user enters QQQQQ, instead of a valid URL, for example), I am not given any information that this is going to fail. It simply puts "Create QQQQ" in the Subj/Obj field

ah, yeah, there should be some information about the creation failing. thats a bug.

> Also, how do you choose the content type of the entity you create in the background (in case this relation supports subject/object of multiple types) - is it based on the attributes of the RDF data?

Hah, this is a long discussion I've had with @sennierer last week and a couple of times before! It would be ideal if it was possible to create the instance based only on the data from the URI and decide which model it should be. But currently we **have** to pass the target model to the method that does the import. And in the relation form you (should) see the `Create ...` option only if there is only one possible entity target type (which is the case for all the relations forms in the entity edit view)
