### ISSUE TITLE
question(apis_entities): should there be a Create option in Merge entities

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1365]
Should it be possible to create a brand new entitiy in APIS while attempting to Merge entities? 

Kind of related to #1364, and if we want offer this feature, then we should fix #1363

![image](https://github.com/user-attachments/assets/42b65564-2083-4498-b185-b44f5b2b5ed1)

**Comment by b1rger** [comment]
> Should it be possible to create a brand new entitiy in APIS while attempting to Merge entities?

I would say no, it should not. It does not really make any sense to first create an instance and then in the same step merge that into another one and delete it again. If the merge form receives a URL as value, it should pass that on to the enrich view.
I created #1396 which changes the default for the autocomplete endpoint to **not** provide the create option.

**Comment by b1rger** [comment]
This `Create...` option is not part of the merge form anymore since 6995a73d6722f379f0d2cb0f22658fb47901e1b8, so I'm closing this issue
