### ISSUE TITLE
Internal, external CSS not formatted equally

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1367]
Indentation is inconsistent between styles in different locations.

Internal:
https://github.com/acdh-oeaw/apis-core-rdf/blob/8ba926298f20faf41f3dced76914c19c2775ea12/apis_core/core/templates/partials/backtotopbtn.html#L1-L9

External:
https://github.com/acdh-oeaw/apis-core-rdf/blob/8ba926298f20faf41f3dced76914c19c2775ea12/apis_core/core/static/css/core.css#L1-L8

See also #1326.

**Comment by b1rger** [comment]
```
grep -r '<style>' *
```
does not list any internal CSS anymore, so I'm closing this
