### ISSUE TITLE
Optimize the Property validity check 

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#14]
When a triple is saved, it is checked if the classes in the subject- and object-side are consistent with the classes allowed in the Property class. https://github.com/acdh-oeaw/apis-core-rdf/blob/77b1ce33f2a677fc9a67e8a2debe59b3311f5ba4/apis_core/apis_relations/models.py#L670

**Comment by sennierer** [comment]
closing as triples will be superseded by class based relations
