### ISSUE TITLE
bug: `APIS_DETAIL_VIEWS_ALLOWED = True`  does not make any difference

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1400]
Despite the setting `APIS_DETAIL_VIEWS_ALLOWED = True`  the user is still forced to login to see the detail page.

And as far as I can tell this ensures that view permissions are always set for Detail views.
https://github.com/acdh-oeaw/apis-core-rdf/blob/4798c98ecbc3578507a87efbe2f04c8ee9bef5e6/apis_core/generic/views.py#L87 

A fix is available in PR #1399 

To Discuss:
1. Do we need this setting at all - it only applies to the "view", create and update views require permissions anyway.
2. By allowing ListView and disabling Detail views we are essentially only stopping the user from seeing the entity details and the relations in the same page.
3. However the "details" of the objects can be seen from the ListView by selecting the columns and the relations of the objects can be seen in the relations list views.

I would like to suggest that we use a single setting to view entities that when set would allow the anonymous user read only access to both list and detail views. Does that make sense?

**Comment by b1rger** [comment]
>     1. Do we need this setting at all - it only applies to the "view", create and update views require permissions anyway.

I think we don't need this setting anymore.

> I would like to suggest that we use a single setting to view entities that when set would allow the anonymous user read only access to both list and detail views. Does that make sense?

At least in one project I worked on, the users did not want to make *all* entities public, but only some of them - which would not work with only one setting. Back then I introduced the `APIS_VIEW_PASSES_TEST` setting, which allows the project to write a simple function to implement custom permission checks

**Comment by b1rger** [comment]
> Oh yes, that makes sense - but what I meant here was having two different settings for list views (`APIS_LIST_VIEWS_ALLOWED`) and detail views (`APIS_DETAIL_VIEWS_ALLOWED`) when list views give access to everything in the entity detail view (by allowing the user to add columns and via relation list views).

Ah, yes, you're totally right! The split is a remnant of old apis and both those settings are simple booleans, so there is no filtering possible with them.


> I am guessing APIS_DETAIL_VIEWS_ALLOWED would also modify the queryset in the list views for anonymous users if they didn't want some entities to be made public.
> 
> In TibSchol I am custom managers for different access tiers, but I'll check if I can use the `APIS_VIEW_PASSES_TEST` instead. thanks.

Yes, please do! I'm still not sure if its a good approach, because the function can get very complex
