### ISSUE TITLE
Next/Prev entities should point to only entities in the queryset that the user is allowed to see  

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1415]
Continuing #1412 

Consider the following ID sequence
1000, 1001*, 1002, 1003*, 1004 where entities marked with * are not accessible to the user.

### Expected behaviour from page 1002:
 - `Prev` takes the user to 1000
 - `Next` takes the user to 1004

### Current behaviour:
- `Prev` takes the user to login page with a redirect to 1001
- `Next` takes the user to login page with a redirect to 1003

I believe for a smooth experience, just like the listview that hides entities that the user doesn't have permissions to see, the next/prev links in the detail page should only link to the next/prev entities in the listview queryset that the user is allowed to see.

**Comment by b1rger** [comment]
do you know if that works if you use your custom manager solution?

**Comment by b1rger** [comment]
> I haven't quite managed to select different custom managers for different user access tiers (fiddling around middleware to get the user data). 

We are already using the `crum` middleware, so you could get the request using the `get_current_request` method - which then gives you the user
