### ISSUE TITLE
apis-entities: disable enrich uri for default URI

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1438]
I think it doesn't make sense to enrich an entity with itself - which is what happens if we call the enrich endpoint with default URI that is created when the entity is created...

https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/apis_entities/templates/apis_entities/partials/linked_open_data.html#L8C1-L9C1
```
<h5 class="card-title">Linked Open Data</h5>
{% if object.uri_set %}
  <ul>
    {% for uri in object.uri_set.all %}
      <li>
        {{ uri.uri | urlize }}
        {% if object.get_change_permission in perms %}
          <a href="{{ object.get_enrich_url }}?uri={{ uri.uri }}"><span class="material-symbols-outlined">update</span></a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endif %}
```

**Comment by koeaw** [comment]
For me, a click on the "... merge data" link (previously: enrich icon) on a local object actually results in weird template output:

![Screenshot 2024-12-02 at 18-12-00 Heldenplatz](https://github.com/user-attachments/assets/f0e477a2-06c0-4e75-9228-f91ea5410ce9)

(Not sure if that's what you meant anyway since you didn't spell it out; adding this just in case.)

**Comment by b1rger** [comment]
> This is because the default URL created when the object is created is wrong, I think. It's wrong in most APIS instances, as far as I know.
> 
> I wouldn't call it a big in the code but in the configuration and consequently the data. The default base URL for all APIS entities comes from the Django settings

The default `APIS_BASE_URI` is [set to the value of `PUBLIC_URL`](https://github.com/acdh-oeaw/apis-acdhch-default-settings/commit/f71b5b7560050132c501eafad1228845c77db343), if exists, since default-settings 1.3. This should be the right choice for most of the APIS instances at the ACDH
