### ISSUE TITLE
bug: pagination size

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1444]
Pagination size defaults to `25` when we set `paginate_by` to `None` as opposed to no pagination - we should either change the documentation to reflect this or make sure that the behaviour matches the documentation.

See @b1rger's comment below ~I don't see the default pagination size in the documentation here: https://docs.djangoproject.com/en/5.1/topics/pagination/#paginating-a-listview but as far as I can tell we are not setting the limit to 25 in our code.~

We pass the value as None and expect to disable pagination - but we get pagination with 25 rows per page instead.

As far as I can tell, the only way  to "disable" pagination is to set the page size to a very high number (higher than the number of rows in the model anyway).

**Comment by b1rger** [comment]
> I don't see the default pagination size in the documentation here: https://docs.djangoproject.com/en/5.1/topics/pagination/#paginating-a-listview but as far as I can tell we are not setting the limit to 25 in our code. We pass the value as None and expect to disable pagination - but we get pagination with 25 rows per page instead.

just FTR: we use django-tables2, which has its own pagination setup. the pagination setting of the listview does not affect the pagination of the table
