### ISSUE TITLE
DateParser: ab and bis in `start_date_written` and `end_date_written`

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1464]
The fields  `start_date_written` and `end_date_written` are used both at the time of data creation and also when displaying the date fields to the user. For parsing correctly into the start and end date fields, we are using the keywords "ab" and "bis" - which stand out when the rest of the APIS is in English. 

How do we get rid of it? I am not a fan of "from" and "to" replacing "ab" and "bis" as they would pose problems when we support multiple languages.

**Comment by b1rger** [comment]
> How do we get rid of it?

I.e. by #1119

**Comment by sennierer** [comment]
Can you come up with suggestions on a language independent language that allows to set "around", "before", "after"...
We can use that as a fallback when no parsing function is provided in the field
