### ISSUE TITLE
public access of entities

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1470]
Case 1 - an entity that doesn't exist in the database
https://tibschol.acdh-ch-dev.oeaw.ac.at/entity/800/

 ```
{
    "detail": "Not found."
}
```

Case 2 - an entity that exists but not made public
https://tibschol.acdh-ch-dev.oeaw.ac.at/apis/entity/4331/ gets automatically redirected to https://tibschol.acdh-ch-dev.oeaw.ac.at/apis/api/apis_ontology.place/4331/

And we get
```
{
    "detail": "No Place matches the given query."
}
```

Is it okay that we let the user know that the entity of a given pk is of such and such type (Place in this case) and it exists - because the error says there's no matching "Place".

**Comment by sennierer** [comment]
telling people that there is a place with that id is ok. we wont fix this for the moment
