### ISSUE TITLE
sample_project: URIs are created but not linked with the entities

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1473]
https://discworld.acdh-ch-dev.oeaw.ac.at/apis_metainfo.uri/

![image](https://github.com/user-attachments/assets/de9710ca-703d-4c70-b016-e316d2ebb354)

**Comment by b1rger** [comment]
If I create a new object in the discworld instance, it does get an URI assigned. I guess the dangling URIs are a problem with our fixtures.

**Comment by b1rger** [comment]
> Yeah I thought that must've been the case but URI data isn't in the fixture so I guess they're automatically created but not linked to the entity for whatever reason...

Ah, interesting, I didn't know that the URIs are not part of the fixtures. But yes, thats weird. I wonder how the URIs are created then...

**Comment by b1rger** [comment]
https://docs.djangoproject.com/en/5.1/topics/db/fixtures/#how-fixtures-are-saved-to-the-database says:

> When fixture files are processed, the data is saved to the database as is. Model defined [save()](https://docs.djangoproject.com/en/5.1/ref/models/instances/#django.db.models.Model.save) methods are not called, and any [pre_save](https://docs.djangoproject.com/en/5.1/ref/signals/#django.db.models.signals.pre_save) or [post_save](https://docs.djangoproject.com/en/5.1/ref/signals/#django.db.models.signals.post_save) signals will be called with raw=True since the instance only contains attributes that are local to the model.

So I think with "the instance only contains attributes that are local to the model" might mean there is not foreign key to the root model (yet) and thats why the Uri gets created with the `root_model` pointing to `None`.

I'd say lets do what the documentation says and disable the signal for fixture loading
