### ISSUE TITLE
Cannot delete relations if the subj/obj is None

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1489]
When an entity is deleted, then the generic FK fields in Relations model that referenced the deleted object still contain the invalid ID. 

In Update view - when no matching entity is found for this ID then the corresponding `ct and id*` field displays a blank value which can be successfully updated.

However these relations that have invalid subj/obj IDs cannot be deleted 

`subj_object_id`, `obj_object_id` cannot be reset at the moment because they are non-nullable fields. In TibSchol we are currently using the following signal to auto delete corresponding relations when an entity is deleted.   

```
@receiver(pre_delete, sender=RootObject)
def cascade_delete_related(sender, instance, **kwargs):
    Relation.objects.filter(subj_object_id=instance.pk).delete()
    Relation.objects.filter(obj_object_id=instance.pk).delete()
 
```

**Comment by b1rger** [comment]
This was a bug with the relation filter and when fixing this there was a bug in the serializer. 7cd93e70f27ba97cfc7cb95bd324ee2ebd0bac15 and 163f3f85472841de3e553c2042fb89a2da863976 fix this.
