### ISSUE TITLE
Discuss and consider removing apis-labels

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#15]
Unless I overlooked it, I don't see a compelling reason in having a django app apis-labels just for a single use-case. This is ontology-specifics hard-coded in business logic. 

We might be able to replace it with semantic equivalences within apis-ontology module.

further steps from now on:
* discuss this with team at JF

**Comment by b1rger** [comment]
Our JFX protocol says:
```
    Merge-function should be function of rootObject and can be overwritten in ontology
    That allows us to remove apis-labels 
```

What is the connection between the former and the latter? Can't we simply remove `apis-labels`? @sennierer maybe you know what the intention of that second line was...

**Comment by sennierer** [comment]
Second line meant that if we allow for overwriting the merge functionality in ontologies, the ontologies can also take care of storing whatever information they want to keep in whatever model they want to use by adding a pre-delete signal and checking for  the issuer of that signal.
As the one of the main  functions in apis-rdf of the labels model was to keep information (such as the label) of an merged object , we can safely remove it (without loosing functionality).

**Comment by b1rger** [comment]
> Second line meant that if we allow for overwriting the merge functionality in ontologies, the ontologies can also take care of storing whatever information they want to keep in whatever model they want ...

Oke, that should be #142

> ... to use by adding a pre-delete signal and checking for the issuer of that signal.

Not sure how signals are involved.

**Comment by sennierer** [comment]
decided in Jfx:
- we will remove the labels
- however given that merges save information of merged objects in labels we keep it until the data can be moved somewhere else.

**Comment by sennierer** [comment]
related to #242
