### ISSUE TITLE
Drop `browsing/generic_list.html`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#151]
The list template for relations and entities defaults to `apis_entities/generic_list.html` but can be overridden by setting `APIS_LIST_VIEW_TEMPLATE`. This setting is set to `browsing/generic_list.html` in our `base.py` settings file. 

It would be less confusing if we just drop our override and replace the default `generic_list.html`. That means `browsing/generic_list.html` should be moved to `apis_entities/generic_list.html` and the custom setting in `base.py` should be dropped.

**Comment by koeaw** [comment]
Leaving a link to this (in-review) PR here because it deals with one of the mentioned files: https://github.com/acdh-oeaw/apis-core-rdf/pull/150

**Comment by koeaw** [comment]
Just updating to say the above PR with changes to `browsing/generic_list.html` has meanwhile been merged.
