### ISSUE TITLE
Default table sorting

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#156]
**Describe the bug**
The queryset for `GenericListViewNew` currently [gets sorted by `name`](https://github.com/acdh-oeaw/apis-core-rdf/blob/f82851150308ba6bc2a3e7274897fe2f19886ea4/apis_core/apis_entities/views.py#L142), which
1. is a field that won't be available anymore after the switch to reifications and
2. makes for bad UX even now on initial load of a table whose first column is not `name`.

**To Reproduce**
1. In an entity's `table_fields` setting, put a field other than `name` in first place. 
3. Navigate to the entity's default list view.
4. Observe the default sorting of list view table.

**Expected behavior**
Ideally, entity list view tables were always sorted by their first column, i.e. the first field provided in `table_fields` in `APIS_ENTITIES`, on first load/before any manual sorting got applied by the user.

**Screenshots**
Screenshot shows first rows of the default list view for an entity with a setting of `"table_fields": ["id", "name", "relevancy", "fictionality"],`. Note the random sorting of the first column (vs. the alphabetical sorting of the second).

![Screenshot 2023-05-15 at 20-47-29 Browse Figur](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/ccd90f6f-9dd3-4f9a-a137-5ac4b75a02d3)

**Note regarding implementation**
Since other methods in class `GenericListViewNew` also (separately) check for `APIS_ENTITIES`, e.g. `get_table()` [here](https://github.com/acdh-oeaw/apis-core-rdf/blob/f82851150308ba6bc2a3e7274897fe2f19886ea4/apis_core/apis_entities/views.py#L172) and `get_context_data()` [here](https://github.com/acdh-oeaw/apis-core-rdf/blob/f82851150308ba6bc2a3e7274897fe2f19886ea4/apis_core/apis_entities/views.py#L266), I'm wondering if it wouldn't make sense to put this check, which `get_queryset()` would also need for entity-specific sorting, in a separate method that gets called by the others to avoid redundancy?

More generally, wouldn't this be a case of putting such a check in the `__init__` method?

**Comment by koeaw** [comment]
> I think we should simple remove the `order_by` and let the [model options define the default order](https://docs.djangoproject.com/en/4.2/ref/models/options/#ordering)

Ah, I didn't know that that's how it can/should be done.

IIRC I originally introduced the ordering by `name` in the view because Django was throwing warnings (and because `name` would always be the one column set for every entity even if no `table_fields` were provided).

**Comment by koeaw** [comment]
Hm, just tried it out. I guess it does add some adminstrative overhead (or potential for confusion) -> whenever `table_fields` are adapted in `server_settings.py`, the `ordering` setting in `models.py` needs to be cross-checked to make sure it doesn't e.g. contain a field that's not actually displayed (anymore) to the user.

**Comment by koeaw** [comment]
Ohh, also, the setting in `models.py` gets inherited (naturally) unlike `table_fields`. :grimacing: 

The warning I'm getting without any ordering applied, btw., is:

```
UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'apis_ontology.models.MyClass'> QuerySet.
```
though the results _appear_ to be ordered by `id` (?!). Not sure how reliable that is. My assumption was that ordering should always be applied to avoid previous results accidentally appearing again when paginating.

Re: inheritance:  
What I'd like to do is sort most entities by `name` by default – _except_ for their shared parent class, which is the only table for which I want to show an `id` column (as first column; column by which the table should be sorted). If ordering is always recommended, I guess there is no way around setting it for every class separately because I'd need to override the parent class's `id` ordering?

**Comment by b1rger** [comment]
The code this bug report refers to has been refactored and it is now very easy to simply provide a custom queryset or a custom table to override the default behavior. I'm therefore closing this
