### ISSUE TITLE
Discuss `apis_tei`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#166]
In the `apis_tei` app, all the routes are disabled (commented). There are no models. There is one place in `apis_entities` where the `apis_tei` module is used, that is the `EntityToTEI` renderer in `apis_entities.api_renderers` which uses `apis_tei.tei.TeiEntCreator`. Does it make sense to drop the django application and simply move the `apis_tei.tei` module to `utils`?

**Comment by sennierer** [comment]
We need the functionality. However, given that it is based on the vanilla data model we will need to make it more flexible (e.g. allowing ontologies to set their own TEI serializer (for the mapping of attributes).
Also the app is maintained by @csae8092 . Given that its currently only used in vanilla instances. We might want to just copy the important parts and re-implement a similar functionality in apis-rdf. @csae8092 you fine with us copying parts of the app to `utils` module in apis-rdf?

**Comment by csae8092** [comment]
Sure, die whatever you want

**Comment by b1rger** [comment]
This was implemented in b0bea902cf4507569ab256efaf3082799d6bca9d and 199f2f453dab020f556dcb7c8b6b96e17a96e0d7
