### ISSUE TITLE
Discuss `merge` function from listview table

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#168]
The generic list view contains an option to merge entities. If enabled in the `APIS_ENTITIES` setting for an entity, it is possible to choose a `merge` column for the table (one has to fix the `apis_entities.table` module first, I leave that as an exercise to the reader 😜). 

It then looks like this:
![Screenshot 2023-05-26 at 20-01-41 Browse Person](https://github.com/acdh-oeaw/apis-core-rdf/assets/1143280/c8024394-baee-4e3d-9ca5-1fef0c4c71b6)

Apparently it is also possible to delete entities using these checkboxes. Given that the functionality is broken and no one noticed - do we need it? (I think it might be useful, but the implementation as a column could be enhanced - I'm thinking of a static checkbox and combining that with an action menu (delete, merge, duplicate, ...))

**Comment by sennierer** [comment]
Given that its broken I opt for removing it for now and adding a feature issue to the backlog for a reimplementation at a later stage.

**Comment by sennierer** [comment]
remove that for the time being
