### ISSUE TITLE
Discuss `Use edit views` functionality

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#169]
The user menu in the top navbar provides a `Use edit views` checkbox inside a form. It does not do anything and I didn't find a way of sending that form. Apparently it should set the session variable `edit_views`, which is checked in the list tables and then links the `name` column to the edit view of the entity instead of the detail view. Should we fix that or drop it or replace it with something else?

**Comment by sennierer** [comment]
The basic idea of this was to allow researchers to directly jump to the edit view. However, I think that we can ditch the saving to a session variable and just check if someone is logged in. If yes -> edit views, if no -> detail views

**Comment by koeaw** [comment]
> However, I think that we can ditch the saving to a session variable and just check if someone is logged in. If yes -> edit views, if no -> detail views

I myself rarely use edit views but often check detail views, so would find such a (permanent) switch really inconvenient. But can see how it might make sense as default.

> It does not do anything and I didn't find a way of sending that form. 

I think there's something wrong both with the form (possibly negligible) and the checking of the session variable. I've tried to fix this in the past but ultimately didn't manage to.

**Comment by sennierer** [comment]
we create two icons for detail views and edit views. the edit views link will only be shown when users are logged in and have edit permissions. -> keep an additional link (always on the first column, pointing to the detail view)

**Comment by sennierer** [comment]
@gregorpirgie to create PR for implementing a edit column in the table with a pencil icon
