### ISSUE TITLE
Bump Python dep to >= 3.11

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#171]
Python 3.10 introduces `match`, 3.11 comes with `toml`. Our main deployment uses 3.11- can we bump the dependency and use the new features?

**Comment by b1rger** [comment]
we decided to go to 3.11

**Comment by sennierer** [comment]
decided in Jfx, we move to Python 3.11 as minimum

**Comment by sennierer** [comment]
@acdh-oeaw/apis-rdf please note, we decided today to move min requirements of apis to python >= 3.11. Please answer to this ticket in case this might break your setup.
