### ISSUE TITLE
Introduce `core` module

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#179]
There are a lot of parts in apis that are used by various `apis_core` modules: generic templates, generic views, ...
I suggest to create a module `core` (as in Django) or `base` or `generic` where we put those. ATM some of them are part of `apis_metainfo`, others are part of `apis_entities`...

**Comment by sennierer** [comment]
good idea, I put it on the agenda

**Comment by sennierer** [comment]
agreed in the JFX
decided to call it `core`
rename `apis_core` in the future #203

**Comment by b1rger** [comment]
That has been implemented during 082d798368fed36aa62fa1da62dd9b860f0816ee
