### ISSUE TITLE
Drop fundament dependency

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#180]
`apis_core` can live with bare bootstrap. Everything CI related should be implemented in `apis-webpage`

**Comment by sennierer** [comment]
absolutely agree (on removing fundament), but what does the removing of bootstrap have to do with CI?
Btw., I think we already agreed on removing fundament (removing the needs-attention batch)

**Comment by b1rger** [comment]
> what does the removing of bootstrap have to do with CI?

CI as in corporate identity ;)
