### ISSUE TITLE
Possible Refactor: re-think factory methods that create classes and class instances

### ISSUE THREAD

**Issue by gregorpirgie** [acdh-oeaw/apis-core-rdf#182]
As an introduction, please read the discussion in PR #181 under the question about the __init__ function used in the apis_entities.tables.py factory function: [link to thread](https://github.com/acdh-oeaw/apis-core-rdf/pull/181#discussion_r1212349441).

# Description of the current pattern: 

We use factory methods at several places in our code-base when generic versions of specific classes are needed.  (see a list of the places where it is used below).
But in the current implementation, the whole class and a single instance are created each time we would actually just need an instance of the generic class. 

Also, there is often no clear distinction between code that should be used on a per-instance basis and computed at runtime (request time of an instance) and code that is applied to the whole class.

# What is the issue with that: 

- the code is harder to reason about, because we treat classes like instances and we can do that because the class is re-created on each request and then garbage-collected
- specifically, we have instance-scoped logic in the class body, that should actually live in the init method.
- but also we re-create classes and instances for each request (after which they are garbage collected!), which is neither resource-aware, nor does it follow the OOP logic and the intended use of the libraries we make use of that provide those classes that we create at runtime.

# Suggested Refactor: 

- refactor the classes themselves and make clear distinctions between instance-scoped logic and settings and class-scoped logic and settings.
- either move the generic logic also in the init function, and get rid of the factory method (which in most cases should not be possible, I think, as generic settings are needed also in the `class meta block`)
- or leave the factory methods as they are (but still, refactor the class body to be more semantically and logically clear), but on startup, create all possible variants of the generic classes, store them in a dictionary or another appropriate datastructure and then each time an instance of a variant of the class is needed, retrieve the pre-created class from the storing datastructure (not the factory method) and create a new instance of it. 
- this way, the classes would stay alive and are not garbage collected. 

# Where the pattern is used atm :

These I could find: 

## apis_core/apis_relations
- in `rel_filters.py` - factory: `get_generic_relation_filter` ([see here](https://github.com/acdh-oeaw/apis-core-rdf/blob/c35d13bcf026b9946c3ec0eb908b87880a246e02/apis_core/apis_relations/rel_filters.py#L92))
- in `tables.py` - factory: `get_generic_relation_listview_table` ([see here](https://github.com/acdh-oeaw/apis-core-rdf/blob/c35d13bcf026b9946c3ec0eb908b87880a246e02/apis_core/apis_relations/tables.py#L135))

## apis_core/apis_metainfo
- in `browsingviews.py` - factory: `get_entities_table` ([see here](https://github.com/acdh-oeaw/apis-core-rdf/blob/c35d13bcf026b9946c3ec0eb908b87880a246e02/apis_core/apis_metainfo/browsingviews.py#L16))

## apis_core/apis_entities
- in `filters.py` - factory: `get_list_filter_of_entity` ([see here](https://github.com/acdh-oeaw/apis-core-rdf/blob/c35d13bcf026b9946c3ec0eb908b87880a246e02/apis_core/apis_entities/filters.py#L379))
- in `forms.py` - factory: `get_entities_form` ([see here](https://github.com/acdh-oeaw/apis-core-rdf/blob/c35d13bcf026b9946c3ec0eb908b87880a246e02/apis_core/apis_entities/forms.py#L37))
- in `tables.py` - factory: `get_entities_table` ([see here](https://github.com/acdh-oeaw/apis-core-rdf/blob/c35d13bcf026b9946c3ec0eb908b87880a246e02/apis_core/apis_entities/tables.py#L29))

**Comment by b1rger** [comment]
Yes! Please lets get rid of those factories!

**Comment by koeaw** [comment]
(updated post to include convenience links to referenced communication & code)

**Comment by b1rger** [comment]
Most of that stuff has been refactored by now -> closing
