### ISSUE TITLE
Introduce `ruff` linter

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#190]
[ruff](https://lwn.net/Articles/930487/) is the new hot shit in Python linting. I suggest we introduce it into our workflow. This would entail:

- [ ] run `ruff` on the existing codebase and fix all errors
- [ ] create a github action that runs ruff automatically on PRs and branches

**Comment by sennierer** [comment]
good idea from my perspective.
I put it on the agenda of next week and will test it until then

**Comment by sennierer** [comment]
decided in JFX to introduce ruff
also as action in GitHub https://github.com/ChartBoost/ruff-action
> there should be a dev-setup documentation #204
