### ISSUE TITLE
Include new sections in project docs: coding conventions + setup process

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#204]

**Comment by sennierer** [comment]
should include:
- linters, formatters...
- git strategies
- also specific setups for IDEs:
    - vscode
    - vim
    - ....

**Comment by b1rger** [comment]
Given that no one cared to implement this in over a year, should we just close the issue? I'm not even sure why we would want to document vim specific setup...

**Comment by sennierer** [comment]
agree, we close this one
