### ISSUE TITLE
Implement vocabularies in apis-rdf

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#213]
In Nomansland, vocabularies are urgently needed. While we agreed to remove vocabularies over rdf classes defined in apis-ontology the vanilla approach might be working still, as it's quite trivial wiring. And transfering this vanilla approach data to another architecture later on is straight-forward too as it's just some relations to a model where neither the relation nor the target model carry much complexity.

I will go for a crude-but-working approach.

**Comment by b1rger** [comment]
Collections (of vocabularies) have been implemented in cbad572207d419e5a8ed5be1d8bb8315054cd407
