### ISSUE TITLE
URIs - one per entity or multiple?

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#221]
When adding a relation, load_subj_obj_prop seems to assume that an object can have only one Uri object - Line 174 `Uri.objects.get(root_object=entity_instance_other)`, but I imagine the intention is to allow multiple URIs for an entity (as far as I can infer from the detail view that has the label "URI(s")

**Comment by sennierer** [comment]
https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis_core/apis_relations/forms2.py#L147 needs to be changed to `Uri.objects.get(root_object=entity_instance_other, uri__startswith=settings.get("APIS_BASE_URI"))`

**Comment by b1rger** [comment]
We hit that bug too and it should be:
```
Uri.objects.filter(root_object=entity_instance_other, uri__startswith=getattr(settings, "APIS_BASE_URI", "")).first()
```

**Comment by b1rger** [comment]
It would be great if that would be fixed
