### ISSUE TITLE
Replace `guardian` with custom solution

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#224]
Django guardian provides object level permission for django. In the current `apis-core-rdf` codebase, it is not really being used - there are some old code snipplets where permissions get set, triggered by signals, but nothing gets checked anywhere.

I think we don't really need *object level* permissions - I think, most of the time we only need to check if an object is public and this check should be based on other attributes, like `object is part of collection`. And we only need those for the listview and the detailview and the API list and detail endpoints, because all the other views/endpoints (create, update, delete, merge, duplicate) only work for authenticated users anyway.

I propose to replace guardian with two Mixins: `DetailViewAccessMixin` and `ListViewAccessMixin`, both providing methods for downstream ontologies to hook into add custom checks

**Comment by sennierer** [comment]
Maybe also/instead add a decorator
