### ISSUE TITLE
Permissions to display relations form

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-core-rdf#225]
User needs to be set as Administrator to see form for adding relations

**Comment by sennierer** [comment]
The problem also exists in other projects

**Comment by sennierer** [comment]
ajax requests for loading relation forms are not fired (probably not even added?) when user is not admin.

**Comment by sennierer** [comment]
still working fine in vanilla instances

**Comment by sennierer** [comment]
for rdf we might want to remove the checking of model level permissions. We might want to distinguish between users who are allowed to edit and those who are only allowed to view items.

**Comment by sennierer** [comment]
this has been resolved in recent versions of apis_core
