### ISSUE TITLE
Let ontologies override entity forms

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#238]
It would be great if ontologies would be able to not use the genericentityform, but define a custom for class (probably in the APIS_ENTITIES dict) that should be used as the form in the entities edit view

**Comment by b1rger** [comment]
This also relates to #182 - might be possible to implement this during the refactoring of `get_entities_form`

**Comment by richardhadden** [comment]
Forms at the moment are created with some factory? How about something like, add a setting with custom form overrides:

```python
CUSTOM_FORM_OVERRIDES = {<Model>: <Form>}
```

And if there is a custom form for a particular model class, make the form factory function return that instead?

(Or, a custom `forms.py` file in the ontology, which we automagically import and find the right form, if it is there... if not, fall back to the factory default)

**Comment by b1rger** [comment]
Yes, well, we do already have the `APIS_ENTITIES` dict, so we should probably reuse that for setting the form:
```python
APIS_ENTITIES = {
    "MyEntity": {
         ...
         form = CustomMyEntityForm,
         ...
    }
}
```

I guess a check before this line should do the trick:
https://github.com/acdh-oeaw/apis-core-rdf/blob/7569984bb3a1b27607265e328b51d9fb88b9c452/apis_core/apis_entities/forms.py#L227
