### ISSUE TITLE
Replace `feather`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#243]
We are using the [feather icons](https://feathericons.com/) in various places. They are pretty, but they can only either be used by including the svg in the html source, which clutters the code, or by using the `data-feather="circle"` attribute on an element and then running `feather.replace()`, which is cumbersome, because that means we have to run `feather.replace()` everytime we change something in a DOM where an icon could be affected.

Maybe we can replace it with something that can be used without svg and javascript, directly in html? (bootstrap icons comes to mind, but maybe there are better solutions nowadays...)

**Comment by sennierer** [comment]
replace with something more usable like bootstrap? Or material?

**Comment by gythaogg** [comment]
Material icons and symbols https://fonts.google.com/icons

**Comment by gregorpirgie** [comment]
# Candidates: 

There are a bunch of libraries, but these are the ones most often mentioned and either completely free or with a free tier (with substantial choices). ATM (to my knowledge) we don't use that many different icons anyway. 

Embedding-wise and styling wise they are quite the same. 

## Material Icons
- [link](https://fonts.google.com/icons)

## Bootstrap Icons
- [link](https://icons.getbootstrap.com/)

## Feather Icons
- [link](https://feathericons.com/) 
- According to my sources, the full package of the icons is quite "big" to load, bigger than the others at least. So as we use not that many Icons, maybe we should go for a smaller package. 

## Font Awesome Icons
- [link](https://fontawesome.com/search?o=r&m=free&s=solid&f=classic) (pre-selected a free tier set, but there are others)

–––

I would suggest to discuss which library to choose and how to unify existing Icons in an upcoming JFX. 

# Django-Icons

There is also this library, but all it does is to allow you to define one or multiple icon sets you want to use (f.e. one of the above) and then it creates Templatetags for you, so you can embed icons via those Templatetags. Seems just like syntactic sugar to me. But I include it here if you want to have a look (I just took a brief look): 

- [PyPi Django Icons](https://pypi.org/project/django-icons/)
- [Django Icons Docs](https://django-icons.readthedocs.io/en/latest/)

**Comment by sennierer** [comment]
decided for material icons
@gregorpirgie to create a PR for changing icons to Google Material

**Comment by gregorpirgie** [comment]
I created a sample html page and loaded all existing feather icons that we currently use (in apis-core-rdf - tempaltes) into a table. You find the closest Material Icons I could find next to it. Where multiple alternatives existed, I created additional columns. 

I am not opinionated about this, but if somebody prefers a variant, please comment here. 


<img width="1262" alt="icon_preview" src="https://github.com/acdh-oeaw/apis-core-rdf/assets/78487560/221fd6d7-a823-4195-9919-c2c775c2141e">

**Comment by gregorpirgie** [comment]
While replaciong the feather icons, I saw that some templates also use font-awesome icons. 

For example this template: [relations_detail_generic.html](https://github.com/acdh-oeaw/apis-core-rdf/blob/ee27538eb8364ce095896fdcb48afb2364212adf/apis_core/apis_relations/templates/apis_relations/relations_detail_generic.html)
'fa' and 'fas' signify the font-awesome icons. 

Not many templates use it, but it's not the only one. Not sure if those templates are actively used though. 

I will leave those untouched for the moment. Just note that there is at least one other icon library implemented in our codebase.

**Comment by gythaogg** [comment]
@gregorpirgie Thanks! It looks like the material icons are a wee bit smaller - can we preview how it looks on a random APIS page (the static html of a detail page for example) if it's not too much trouble?

**Comment by gregorpirgie** [comment]
@gythaogg Sure! Here is a direct comparison for detail and edit pages. Note that the "open-book" icon (the bibsonomy reference Icon) is not yet updated, as this needs an integration of the new material icons in the bibsonomy module (I created an issue for that). 

Without tinkering with the size of the icons, the material icons are actually a bit bigger.  But you can style the material icons with css (color, size, etc) also.


Old feather Icons: 
![feather_detail_page](https://github.com/acdh-oeaw/apis-core-rdf/assets/78487560/d0ed0a14-6ca7-4a60-854a-c586afed92b5)
![feather_edit_page](https://github.com/acdh-oeaw/apis-core-rdf/assets/78487560/67780b1e-08a1-4866-881c-fcb916bd43e7)


New Material Icons: 
![material_detail_page](https://github.com/acdh-oeaw/apis-core-rdf/assets/78487560/19b507fd-561e-4fe8-8335-cfcc19b1b7b5)
![material_edit_page](https://github.com/acdh-oeaw/apis-core-rdf/assets/78487560/8442242e-a766-41ad-b10b-118c70412ec2)

**Comment by gythaogg** [comment]
Right! Material looks good to me.
