### ISSUE TITLE
Should aps-core-rdf contain behaviour for expected ontology  data model?

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#246]
For example, the `__str__`  method in TempEntity class checks for the presence of an attribute called "first_name". 

A quick search for hasattr in this repo shows autocomplete3 checks for an attribute called lng - I don't know what feature I am missing because I have named my longitude field "longitude" and not lng

**Comment by b1rger** [comment]
> Should aps-core-rdf contain behaviour for expected ontology data model?

I'd say it should not. But there is still a lot of code that does make assumptions about ontology models. We should try to find them and create issues to replace them with more sensible defaults.

**Comment by sennierer** [comment]
we try to get rid of any assumptions on ontology implementations
