### ISSUE TITLE
Write new relation forms

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#249]
The current handling of relations is weird. The relations for gets rendered to html and is then put into a json object which is fetched by a custom javascript and put into the entity edit page. I suggest to rewrite the whole relation handling. This also relates to #130

**Comment by b1rger** [comment]
Probably the same as #202

**Comment by richardhadden** [comment]
Is there a reason these form sections need to be loaded via ajax at all? Seems very complex, compared to just building the whole template in one go

**Comment by richardhadden** [comment]
See also my comment: https://github.com/acdh-oeaw/apis-core-rdf/issues/252#issuecomment-1630272031

**Comment by b1rger** [comment]
This is now done as part of the new relatios implementation 1799ea63c3c222c075a2006495675dbdc7651315
