### ISSUE TITLE
Let relations only be created one way

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#252]
At the moment a relation can be created from two sides. An example: a person gets a salary. It is now possible to create a `person->get->salary` relation or to create a `salary->isgivento->person` relation. If we want to lookup payments, we do now have to always think of doing the lookup from both sides. Is there any benefit of being able to save the relation in the database in two different forms? Why don't we force the relation to be always saved as `person->get->salary`? We can still create a `reverse()` method on these relations that gives us the other way around, where needed

**Comment by richardhadden** [comment]
For the ManMax use case, I would definitely agree: our approach is certainly to create statements, then link them to entities as required. I'd even go further: it would be more useful to have the Relations column show the _properties_ by which a related entity could be related, rather than hiding that behind the entity _type_ (the collapsing panels).

I guess the current approach works better for legacy-APIS style apps, which were obviously more entity-focused, and could just as easily be linked in either direction.

**Comment by koeaw** [comment]
I'm not sure I fully understand.

Are you saying triples for the same property are saved differently in the DB, depending on which "direction" they are created from (subject or object side)? I think I thought triples would always be saved following the "pattern" used to define the property. I.e. whatever is on the left side in `models.py` is assumed to be the subject,  `name`/`name_forward` is the predicate, what's on the right side is the object. (Whether that's true or not in a grammatical sense – the program doesn't know if a human decides to use passive voice for `name`, thereby effectively flipping subject and object.) 

Maybe this relates to a bug we experienced recently, where some entities can only be connected from one side, not the other. :thinking:

**Comment by koeaw** [comment]
Addentum: I'm assuming no-one wants to get rid of the interface allowing triple creation from either side – which we wouldn't want to lose – but that this is only about how newly created triples are handled in the DB. 

> it would be more useful to have the Relations column show the properties by which a related entity could be related, rather than hiding that behind the entity type (the collapsing panels).

Hmm, I get what you are saying, but in our case, listing the entity types makes more sense. And would make even more sense if they used verbose names, and were filtered down to the ones that can be connected via a property.

Reason being that our team knows exactly which entities (can) go together (and can identify the English model names in places where the German verbose names are unavailable), but would have a harder time keeping all the terse English(-only) property names apart. Even I get confused between a number of similar properties we use between the same two entity types.

**Comment by richardhadden** [comment]
> Hmm, I get what you are saying, but in our case, listing the entity types makes more sense. And would make even more sense if they used verbose names, and were filtered down to the ones that can be connected via a property.

I've done both of these things in ManMax — I think the PRs might already be in Dev actually

**Comment by richardhadden** [comment]
> Hmm, I get what you are saying, but in our case, listing the entity types makes more sense.

Yes, I see why both options are valid, depending on use case. In the case of ManMax, the relationships carry most of the information (concrete entities connected in specific, relatively abstract, ways to statements); in the "vintage" (can we call it this now?) APIS, most of the information was fields on entities, and they were related to different types of things.
