### ISSUE TITLE
Loosen python requirement

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#255]
A `poetry new something` creates a `pyproject.toml` with a Python requirement set to greater or equal to the used Python version. When adding apis-core-rdf as a dependency, this then results in 
```
The current project's Python requirement (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - apis-core requires Python >=3.11, <3.12, so it will not be satisfied for Python >=3.12,<4.0
```

I think there is no need in defining an upper limit for the required Python minor version in apis and we should replace the `python = ">=3.11, <3.12"` with `python = "^3.11"`

**Comment by gregorpirgie** [comment]
I support this. Maybe this could also be considered for all dependencies (to remove unnecessary upper-bounds where possible). 

Would help a lot already to do this for python at least!
