### ISSUE TITLE
Rename `RootObject.name` to `RootObject.deprecated_name`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#299]
We decided that the `RootObject` should have no attribute but an ID - to prepare the removal of the `name` attribute, I propose to rename it to `deprecated_name`. Downstream projects have then time to a) create custom name fields in their entities and b) copy the values from `RootObject.deprecated_name`

**Comment by b1rger** [comment]
CC: @acdh-oeaw/prosnet

**Comment by sennierer** [comment]
problem is about also migrating data if fields are dropped..
@sennierer looks into how difficult it is to write custom migrations that also move data if needed

**Comment by sennierer** [comment]
we also need to look into the code and see where we expect a name field to exist

**Comment by sennierer** [comment]
look through code to find usage of `name` and adapt to `str() function` (stingified version of object) or similar
