### ISSUE TITLE
View `apis_entities.views.generic_network_viz` still needed?

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#308]
Accessing the route `apis/entities/networks/generic/` results in `Reverse for 'generic_vocabularies_autocomplete' with keyword arguments '{'vocab': 'personplacerelation', 'direct': 'normal'}' not found`. The error comes from `apis_entities.forms.NetworkVizFilterForm`.

If its broken, should we fix it or remove it?

If the lattter, we should remove the view, the form and the template in `apis_entities/templates/apis_entities/generic_network_visualization.html`

**Comment by sennierer** [comment]
this is not needed and can be removed
