### ISSUE TITLE
Default values for settings

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#316]
Could we collect the default values for the settings variables in one place, for example in a dict,

    `APIS_DEFAULTS = {"APIS_BASE_URI": "http://apis.info/", ....}` 

and uniformly read them everywhere like so:

    `getattr(settings, 'APIS_BASE_URI', APIS_DEFAULTS['APIS_BASE_URI'])`

so that the default strings are not hard-coded all over the repository.

**Comment by koeaw** [comment]
Linking also to the settings repo for completeness' sake: https://github.com/acdh-oeaw/apis-acdhch-default-settings which contains a large number of APIS-specific variables in its [settings](https://github.com/acdh-oeaw/apis-acdhch-default-settings/blob/main/apis_acdhch_default_settings/settings.py) file.

The repo can be included as dependency as a stopgap solution to (unknown) variables being required to be set. (Or serve as reference, and in the long-term help get rid of those variables.)

**Comment by koeaw** [comment]
> If there are unknown variables required to be set, then thats a bug.

I meant "unknown" in the sense of "I/you/we might not actually know what variable X does" and was perhaps using "required" a bit loosely. E.g. `APIS_BASE_URI` is not _strictly required_ to be set, but the defaults it falls back on are useless and will produce nonsense data in your DB, so you'd better make sure it is set.

> The references repository does in fact not use the acdh-specific default settings

Ah true, it doesn't incorporate them – I think I even asked if that didn't render the dependency redundant when we met last week? Forgot about that, sorry, only remembered this was a repo which included it in its dependency list.
