### ISSUE TITLE
css of autocompletes is faulty

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#330]
in autocompletes the selection and the default text are not in the middle of the line
![screenshot-127 0 0 1_8001-2023 10 10-11_40_25](https://github.com/acdh-oeaw/apis-core-rdf/assets/499265/9f79deba-f180-4d09-98d9-4f872bf8a305)
setting `line-height: initial` for the span that holds the autocomplete fixes that
![screenshot-127 0 0 1_8001-2023 10 10-11_42_15](https://github.com/acdh-oeaw/apis-core-rdf/assets/499265/cc45369d-9b48-4db7-9181-a4da6b3101ea)
-> there might be a better fix though

**Comment by koeaw** [comment]
> setting `line-height: initial` for the span that holds the autocomplete fixes that

To add to my comment from last week (above): when I looked at the CSS of this same-ish problem I came across, I noticed that yeah, there's a mismatch between font size and line height (and height).

The computed default `line-height` would/should be 24px for the computed `font-size` of 16px (1rem) of the last 3 spans which contain one another, but it's set to 28px. The _next_ `<span>` wrapping those 3 additionally has its computed `height` set to 28px when it should be 38px by default.

**Comment by koeaw** [comment]
It's these four (copy/paste from my browser, minus the span with the dropdown arrow):

```
<span class="select2-selection select2-selection--single listselect2 form-control" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-id_entity-container">
  <span class="select2-selection__rendered" id="select2-id_entity-container">
    <span class="select2-selection__placeholder">
      <span>Type to get suggestions</span>
    </span>
  </span>
</span>
```

**Comment by b1rger** [comment]
I think this might be [this issue](https://github.com/yourlabs/django-autocomplete-light/issues/1055) - so maybe moving to bootstrap 4 might solve the issue for us

**Comment by koeaw** [comment]
[Later comments](https://github.com/yourlabs/django-autocomplete-light/issues/1318#issuecomment-1460127046) in a newer issue seem to indicate this is indeed a Bootstrap problem – with [select2](https://github.com/select2/select2) – and that it persists in Bootstrap 4.

Suggested fix is: https://github.com/apalfrey/select2-bootstrap-5-theme

**Comment by koeaw** [comment]
Ah, I guess you meant to say Bootstrap 5 anyway!
