### ISSUE TITLE
Get rid of `additional_serializers`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#338]
The `additional_serializers` logic adds a lot of code without adding that much value:
https://github.com/acdh-oeaw/apis-core-rdf/blob/b11352dbfa29ce9f062b626c224a4f62829ffd4f/apis_core/api_routers.py#L486

In fact, it is one of the last places that hardcodes the module name `apis_ontology`.

But it is easy to add additional API endpoints by simply following the DRF manual, whithout having to know any custom APIS internals. Therefore I propose to remove the `additional_serializers` functionality

**Comment by sennierer** [comment]
@sennierer to ask Katharina if she is using this
