### ISSUE TITLE
Main menu not properly responsive – missing icon

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#344]
**Describe the bug**
The CSS for the "burger" icon to open the main menu on small screens clashes with Django's CSP settings, which means the icon doesn't get displayed at all, which effectively makes it impossible to navigate our apps on mobile devices.

Corresponding issue reported over at fundament:
https://github.com/acdh-oeaw/fundament/issues/20

I'd like to integrate my (temporary) solution into `webpage` since it's unclear when/if this'll get fixed on fundament's side. I'll open a PR here since `webpage` hasn't finished moving to https://github.com/acdh-oeaw/apis-webpage yet, but can also move the PR there if that turns out to be more convenient.

**Comment by b1rger** [comment]
Closing, as fundament is neither used in `apis-core-rdf` nor `apis-webpage` anymore
