### ISSUE TITLE
class based permissions given to users are ignored

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#352]
we replaced object level permissions managed by guardian with a simpler built in solution in https://github.com/acdh-oeaw/apis-core-rdf/issues/224

However, APIS (and more general Django) should still respect class based permissions set in the admin backend, but it doesnt. Every logged in user can save objects, even if he/she doesnt have edit permissions

**Comment by b1rger** [comment]
I think permission checks should be done in the views, for example [with the `permission_required` decorator](https://docs.djangoproject.com/en/5.0/topics/auth/default/#the-permission-required-decorator). The use of permissions in the template is merely a UX issue, not a authorization issue

**Comment by koeaw** [comment]
> I think permission checks should be done in the views

Does this work with our generic views? The permissions I've seen – both in the admin interface and how they are constructed in e.g. the edit view linked above – are super fine-grained, i.e. meant to be on a per entity level.

I guess this would require determining the entity in an `__init__` method and then passing it on to decorators set on other methods like `get` and `post`? (?!)

Do even earlier permission checks make any sense at all? The linked page doesn't seen to mention `permission_required()` in connection with urlpatterns, but it's [given as example here](https://docs.djangoproject.com/en/4.2/topics/class-based-views/intro/#decorating-in-urlconf).

I find that last line at the bottom, "This approach applies the decorator on a per-instance basis. If you want every instance of a view to be decorated, you need to take a different approach." confusingly worded; at first I thought it was missing a "don't" in the second sentence but I guess what it's trying to say is that this will ignore the view completely if the permissions check fails – which, yeah, I thought was obvious –, so don't use this if what you actually need is more control over how the view is processed _once it is called_. Anyway, I remember @sennierer saying in a JF we can't do permissions checks on a per-instance basis and I guess that wasn't meant with regard to _checking_ for permissions but with _setting_ them in the first place. (?) And so maybe checking for them this way is overkill/unnecessary/less performant/similar.

**Comment by b1rger** [comment]
> > I think permission checks should be done in the views
> 
> Does this work with our generic views? The permissions I've seen – both in the admin interface and how they are constructed in e.g. the edit view linked above – are super fine-grained, i.e. meant to be on a per entity level.

Hm, you're right that this might be tricky, but I'm sure its doable - if not with the `permission_required` decorator, then with the `user_passes_test` decorator. In the test method we would have to find out the model type like we do in the `EntityMixin` and then we can check the permission.


> [...] I remember @sennierer saying in a JF we can't do permissions checks on a per-instance basis and I guess that wasn't meant with regard to _checking_ for permissions but with _setting_ them in the first place. (?) 

I think this refers to the _instance_ of a _model_ but the documentation talks about the _instance_ of a _view_
