### ISSUE TITLE
Update poetry.lock

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#36]
The `poetry.lock` file does not seem to be up to date and having it in the
repository leads to problems when poetry tries to solve version dependencies:

```
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Because apis-core depends on pandas (^1.5.3) which doesn't match any versions, version solving failed.
```

If we do not keep the file up to date it might be better to just drop it.

**Comment by sennierer** [comment]
actually the suggestion is to keep lock files in git as the installation is then equivalent to your local installation. also when we really drop it we would need to add a `poetry lock` to the docker file. So I suggest we get used to keep lock file and toml file in sync and keep both in the repo.
