### ISSUE TITLE
Integrate `apis_entities.api_urls` into `apis_entities.urls`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#379]
Evaluate if all the urlpatterns in `api_urls` are actually needed. Same for `urls`

**Comment by b1rger** [comment]
* `apis/api2/savenetworkfiles/`: a route for uploading files and saving them in `downloads` - I guess that can be removed
* `apis/api2/getorcreateentity/`: a route for getting or creating an entity based on a URI or some other string containing entity data - I'd say there are more useful API endpoints for doing that
* `apis/api2/entity/<int:pk>`: a route for getting the entity in different formats - this is the same as `/entity/<int:pk>` - but that has to be configured on project side, whereas the `apis/api2/entity/<int:pk>` route is shipped with APIS; nonetheless, I think this should be removed and the significance of the view called by `/entity/<int:pk>` (`apis_entities.apis_views.GetEntityGeneric`) should be documented, as this is the main entrypoint for exporting entities in different formats

opinions, @acdh-oeaw/prosnet , especially @sennierer ?

(This issue is now basically identical with #266 )

**Comment by sennierer** [comment]
We should definitely get rid of all the `api2/` routes and include what is needed in the `api/` routes.
- `apis/api2/savenetworkfiles/` is not needed
- not sure about `apis/api2/getorcreateentity/` as this was used for the possibility to directly create an entity entry from an reference resource URI. Not sure which other API route provides this functionality.
- `/entity/<int:pk>` should allow via content negotiation to be automatically redirected to the html detail page or retrieve whatever format (json, RDF, TEI) was requested
