### ISSUE TITLE
Fix Python requirement

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#38]
When using `poetry install` on the `dev` branch, it fails to solve version requirements:

```
The current project's Python requirement (>=3.7,<3.9) is not compatible with some of the required packages Python requirement:
  - pandas requires Python >=3.8, so it will not be satisfied for Python >=3.7,<3.8

Because pandas (1.5.3) requires Python >=3.8
 and no versions of pandas match >1.5.3,<2.0.0, pandas is forbidden.
So, because apis-core depends on pandas (^1.5.3), version solving failed.
```

Given we depend on a version of pandas that requires Python >= 3.8 we could
simply bump the Python requirements of `apis_core` to >=3.8?

**Comment by koeaw** [comment]
I've previously asked about an upgrade to `Python >=3.8.1` (for other reasons) but unfortunately didn't receive a response. Will link you to the relevant messages over in MM.
