### ISSUE TITLE
Citation template for References

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#388]
Tibschol researchers wanted to be able to add comments to entities (and relationships) where they can cite the Zotero references in a particular way. 

I'm currently doing this by showing the bibsonomy id in the apis database in the list of references once they add it, and asking them to add the citation text like so.
 
Some text `<< citation text to be linked [apis_bibsonomy id]>>` more text `<< another citation text to be linked [another apis_bibsonomy id]>> more text`

And parse this to display the field with links to references.

Have I missed some feature of apis_bibsonomy that allows this more elegantly?

**Comment by sennierer** [comment]
create a new issue in apis-highlighter-ng

**Comment by gythaogg** [comment]
https://github.com/acdh-oeaw/apis-highlighter-ng/issues/21
