### ISSUE TITLE
List view column sorting fails when a column is a computed property

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#391]
My model has a cached property that I am including in the list view by specifying it in the server settings. When I click on the column name of this cached property I am taken to an "Field error" page that contains the below exception.

`Cannot resolve keyword <property name> into field. Choices are: <list of all attributes of the model and those inherited from the temp entity class> 
`
This is only a problem while sorting - the column shows values from the computed property alongside other attributes

1. Create a property in a model using the `@property` or `@cached_property` decorator   
2. Add this property to the list of fields in the list view for the model
3. Go to the list view and try to sort it by clicking on this property 

**Expected behavior**
If sorting on computed properties is not possible, the title could appear as plain text instead of links.

**Comment by b1rger** [comment]
Custom tables are now overridden by creating a custom table that is named after the model class (i.e. `tables.PersonTable` in your ontology app) - if you want to include a field in your table that should not be orderable, please use a [column](https://django-tables2.readthedocs.io/en/latest/pages/api-reference.html#django_tables2.columns.Column) that has the `orderable` argument set to `false`
