### ISSUE TITLE
Create Mixins for common entity types

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#403]
Person, Place, Event, ...?

**Comment by b1rger** [comment]
Added the `needs-attention` label, because we have to discuss how we want to implement this - I guess we don't want to implement *every* layer of cidoc crm

**Comment by sennierer** [comment]
There should be an easy possibility to add vocabularies to type something #514 
We should create an mixin that allows to include a SKOS compliant vocabulary in the ontology #441

**Comment by sennierer** [comment]
we discuss that in extended Jfx 24th of Jan 2024
