### ISSUE TITLE
Run black on the whole repository

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#42]
The [black documentation](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html) writes (emphasis by me):

> when migrating your project’s code style to Black, reformat everything and commit the changes (**preferably in one massive commit**)

[and](https://black.readthedocs.io/en/stable/faq.html#is-black-safe-to-use):

> Black is strictly about formatting, nothing else. Black strives to ensure that after formatting the AST is [checked](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#ast-before-and-after-formatting) with limited special cases where the code is allowed to differ. If issues are found, an error is raised and the file is left untouched.

Therefore I propose to just run black on the whole codebase instead of cluttering the git history with small formatting commits.

**Comment by steffres** [comment]
Sounds good to me.

**Comment by koeaw** [comment]
I'm very much in favour of this but suggest we don't go with the most recent stable release of Black because it removes _all_ blank lines between comments – which decreases readability in general, and might really mess with our files since there is still lots of (temporarily) commented code in there.

**Comment by b1rger** [comment]
> I'm very much in favour of this but suggest we don't go with the most recent stable release of Black because it removes _all_ blank lines between comments – which decreases readability in general, and might really mess with our files since there is still lots of (temporarily) commented code in there.

Just to clarify: you're referring to version 23.01 as the most recent stable release, but using 22.12 would be ok?

**Comment by koeaw** [comment]
Yup, sorry, was going to link issues/comments related to this, but it took me a bit longer than expected to find them again: https://github.com/psf/black/issues/3555 and https://github.com/searxng/searxng/pull/2159#issuecomment-1425723977

**Comment by steffres** [comment]
I merged the fat commit yesterday, so feel free and black to whole repo please.

**Comment by steffres** [comment]
What's the character line width setting?

**Comment by b1rger** [comment]
Black defaults to 88 chars and we don't have an override: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length

**Comment by steffres** [comment]
It can be overriden: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length

But I don't advocate for it anyway, eventhough I personally prefer 100 as I tend to be verbose with naming. 

Since the apis project is moving into a much more collaborative dev setting by now, it's reasonable to stick with defaults.

**Comment by return42** [comment]
> Yup, sorry, was going to link issues/comments related to this, but it took me a bit longer than expected to find them again: [psf/black#3555](https://github.com/psf/black/issues/3555) and [searxng/searxng#2159 (comment)](https://github.com/searxng/searxng/pull/2159#issuecomment-1425723977)

Just FYI: the issue has been solved since https://github.com/psf/black/pull/4060 has been merged .. was a long discussion .. but finally it becomes good :-)

**Comment by b1rger** [comment]
> > Yup, sorry, was going to link issues/comments related to this, but it took me a bit longer than expected to find them again: [psf/black#3555](https://github.com/psf/black/issues/3555) and [searxng/searxng#2159 (comment)](https://github.com/searxng/searxng/pull/2159#issuecomment-1425723977)
> 
> Just FYI: the issue has been solved since [psf/black#4060](https://github.com/psf/black/pull/4060) has been merged .. was a long discussion .. but finally it becomes good :-)

Thanks a lot for the notification! Much appreciated!
