### ISSUE TITLE
come up with a solution for using SKOS like vocabularies in apis-rdf

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#441]
[SKOS](https://www.w3.org/TR/skos-reference/) is W3C standard for vocabularies. Vanilla had a simplified version of this standard implemented and also allowed to serialize the vocabs to SKOS conform RDF.

We want to have the possibility to:
- easily add vocabs classes to APIS RDF instances (e.g. by providing a SKOS concept base class)
- and investigate how we could re-use already published vocabs (e.g. from [ACDH-CH Vocabs](https://vocabs.acdh.oeaw.ac.at/en/))

**Comment by sennierer** [comment]
@gregorpirgie and @richardhadden could you add comments on SKOS/Vocabs here if you have some?

**Comment by b1rger** [comment]
I think this should be a separate app (as in: doesn't have to be part of apis-core)

**Comment by b1rger** [comment]
Also related: #213

**Comment by sennierer** [comment]
absolutely agree on that it shouldnt be part of apis-core
