### ISSUE TITLE
Leftover references to TempEntityClass fields

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#457]
Even though I generally cannot get `GenericRelation`s to show up at the moment (see #456), one `GenericRelation` which shares a name with a field in `TempEntityClass` (`status`) can be added to our `APIS_ENTITIES` settings just fine. I.e. it doesn't throw an error but actually shows up as a column in the table.

I'm assuming this is due to some leftover hardcoded references to `TempEntityClass` fields (our reworked models don't inherit from that class anymore). The "additional columns" dropdown also contains fields which I associate with `TempEntityClass`, like various start/end dates.

**Comment by b1rger** [comment]
I'm not really sure what this issue is about, can we close it? `APIS_ENTITIES` is gone, `TempEntityClass` is gone...

**Comment by koeaw** [comment]
> I'm not really sure what this issue is about, can we close it? `APIS_ENTITIES` is gone, `TempEntityClass` is gone...

Yes, I'd assume so! -> Closing.
