### ISSUE TITLE
Default search for Entities

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-core-rdf#459]
With `name` being removed as a default searchable field, it will be necessary to configure which fields should be searched (using settings) for all models. (In MaxMax, we have 92 models so far, so this is a lot of configuration!)

**Describe the solution you'd like**
A generic "search" box, in the absence of any other defined search fields, that looks at all `CharfField`/`TextField` fields and performs an `icontains` query.

Preferably, the search terms should be tokenised: in ManMax, we have labels such as "Massimiliano (Maximilian) Sforza", which means that a simple `icontains` lookup will not match the query "massimiliano sforza". A better approach might be to tokenise the search string, and perform an `icontains` lookup for both terms. This can be extended to run with an OR over each field:

```python
search_string = "Massimiliano Sforza"

search_tokens = search_string.lower().split(" ")  # Tokenise the search string

# Get all fields on the model that are instances of CharField or TextField
fields_to_search = [field.name for field in <TheModelClass>._meta.fields 
         if isinstance(field, (CharField, TextField))
     ]

# Create query object
q = Q()

# For each token...
for search_token in search_tokens:
    # OR together Q objects for each field for a given token
    # and AND together these (i.e. must find each token in at least one of the fields)
    q &= functools.reduce(
        lambda acc, field_name: acc | Q(**{f"{field_name}__icontains": "X"}), 
        fields_to_search, 
        Q()
    )

# Run the query
results = <TheModelClass>.objects.filter(q)
```

This approach is implemented in ManMax, and is performant when searching for multiple tokens across two fields (one label `CharField` and one `TextField`) on approximately 8,000 entities

**Describe alternatives you've considered**
Another option, if all APIS instances are using Postgres, is to build a full-text search field, and use this as the default search. (see https://pganalyze.com/blog/full-text-search-django-postgres) This is probably more efficient, and will produce better search results.

Could be implemented by adding a migration, as recommended in this article.

**Comment by b1rger** [comment]
I think it would be great to
- [ ] add a filter that implements the logic you proposed in the issue description (probably in `apis_core.utils.filtermethods`, because thats where similar filters are located
- [ ] add a manager or extend the `model.Manager` to the `RootObject` which provides a method that calls the filter (maybe called `search(value: str)`
- [ ] add another filter, that does the same with postgresql and make that filter used by `search` if postgres is used

**Comment by b1rger** [comment]
This is now implemented using the `generate_search_filter` method:
https://github.com/acdh-oeaw/apis-core-rdf/blob/d8649d7d907d07f2ef6b3e0def374d52645d46cc/apis_core/generic/helpers.py#L11

which is used in the default autocomplete and in some other parts of the code
