### ISSUE TITLE
Implement equivalent of detail_view_exclude setting for entity edit views

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#460]
`APIS_ENTITIES` allows setting of a list of field names with key `detail_view_exclude` to suppress rendering of fields in an entity's detail view.

It would be useful to also have an `edit_view_exclude` option available for fields which aren't meant to be filled in by users. (Our use case: `ForeignKey`s to data sources which are only meant to be set by/during data imports.)

**Comment by b1rger** [comment]
If you set editable to false, they shouldn't show up in both the form and the detail view: https://docs.djangoproject.com/en/4.2/ref/models/fields/#editable

**Comment by koeaw** [comment]
For our use case, I need them to show up in all views which display information, but not in ones where users can change an entity object's data.

CC @gythaogg you were looking for what the `detail_view_exclude` setting takes care of!

**Comment by b1rger** [comment]
> For our use case, I need them to show up in all views which display information, but not in ones where users can change an entity object's data.

Then you can use the `editable` argument and add the property to the detail view template

**Comment by koeaw** [comment]
> Then you can set the `editable` argument to `False` and add the property to the detail view template

Thanks, I'll try that.
