### ISSUE TITLE
Refactor entity-related (self) variables for more transparency/better readability

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#461]
The worst offender of the bunch is probably `self.entity` (used in e.g. views), because it's never quite clear which value it contains, but `self.entity_model` isn't great either.

Proposals for new names or replacements:

```
self.entity_class  # class object
self.entity_class_name  # actual class name (incl. original formatting, e.g. PhysicalObject)
self.entity_slug  # sluggified version of class name usable for e.g. URLs
self.entity_verbose_name  # Meta verbose_name
self.entity_verbose_name_plural
```

Re: `self.entity_slug` – I feel like Django supports sluggifying camel-cased names with underscores, which I'd actually find preferable for some of our longer class names. What we currently use for URLs is just a lower-cased version of the class name, I think.

Re: `self.entity_verbose_name`: if `verbose_name` isn't set in `Meta`, Django derives/interprets it from the class name, so we shouldn't have to come up with an alternative in case it's missing. (?! see [Django docs](https://docs.djangoproject.com/en/4.2/ref/models/options/#verbose-name)).

`self.entity_name` could also work for (full, original) class name, but AFAIR we've used it for other name variations as well, so I guess not everybody shares my opinion that this would be the most logical value.

A place where some of these are currently set is [EntityMixin](https://github.com/acdh-oeaw/apis-core-rdf/blob/5b2bfd6de18e074edcc52282943e054d06e19f39/apis_core/apis_entities/mixins.py#L8). Old code comment by me suggesting we clean these up [here](https://github.com/acdh-oeaw/apis-core-rdf/blob/5b2bfd6de18e074edcc52282943e054d06e19f39/apis_core/apis_entities/views.py#L172).

**Comment by b1rger** [comment]
I agree that this can be confusing. I think most of the variables are not needed or used anyway, so they can be removed. For example, everything that can be derived from an object (i.e. the class name, the verbose name, etc) should not exist as a separate variable in a view dealing with the object.

Regarding the naming of the variable, thankfully Django already comes with its own naming scheme: [natural keys](https://docs.djangoproject.com/en/5.0/topics/serialization/#topics-serialization-natural-keys). They consist of `app_label` and `model`, which is also what the [ContentTypes framework uses](https://docs.djangoproject.com/en/5.0/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentTypeManager.get_by_natural_key)

**Comment by koeaw** [comment]
> For example, everything that can be derived from an object (i.e. the class name, the verbose name, etc) should not exist as a separate variable in a view dealing with the object.

Do you mean these variables should already get set earlier, like in the mixin I linked to? Or that the values shouldn't be separated out into variables at all?

I personally prefer separate variables for readability, especially when it comes to e.g. passing values into dictionaries (like the `context` dicts in the views), or when I know I'll be reusing the same values in several places. I just find short, succinct variable names much easier to parse than long strings like `self.instance._meta.get_field(field)` or whatever. But I can see why this would be a minority opinion.

**Comment by b1rger** [comment]
The Mixins and the Views this issue probably refers to have been removed in 45de48bea2b81823873066820a079635b8d7a04a, so I'm closing this. If the issue still exists, please reopen with pointers to the code parts
