### ISSUE TITLE
Unhelpful hints about classes on frontend + whitespace issue

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#464]
**Describe the bug**
The `model.__doc__` value we use to inject docstring information into the frontend, where it can be accessed via hover tooltips, is only useful for classes which actually have a docstring. For classes which don't, `__doc__` seems to fall back onto the class definition.*

Additionally, the resulting `<abbr>` HTML tags seem to mess with whitespace: the class name may be preceded by a newline, though I'm not entirely sure if that is to do with the formatting and/or length of the docstring contents (which go into the `"title"` attribute of the `<abbr>` tag) or the way the tag is included (via templatetags).

**Example:**
Looking at the classes in the "Relations" menu, I see this issue with the "Property" class but not with "Triple" (neither of which currently has a docstring).

**Screenshot:**
![Screenshot from 2023-12-07 16-02-11](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/2f2062b3-ad26-4c32-98f3-e018004f192a)

---
*A cursory look at the Python docs [suggests](https://docs.python.org/3/reference/datamodel.html#custom-classes) `__doc__` is supposed to default to `None` when there is no docstring. The behaviour I'm seeing, however, [mirrors that of](https://docs.python.org/3/library/inspect.html#inspect.getdoc) `inspect.getdoc()`.

**Comment by b1rger** [comment]
Using the new `generic` base views, the class information is not displayed in the frontend anymore, therefore closing this
