### ISSUE TITLE
DeleteView doesn't work for projects which don't use TempEntityClass

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#485]
Issue for WIP PR #458.

**Describe the bug**
As I started to work on #437, I noticed I couldn't get `GenericEntitiesDeleteView` to work at all because it still refers to `TempEntityClass`.

Once I'd fixed that, the confirmation template for deletion, which is _not_ entity-specific but [shared between views](https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/core/templates/confirm_delete.html), wouldn't show me any information on what exactly I was deleting.

While looking at the HTML, I also noticed that it was generally off in places, e.g. buttons which belong together don't sit next to each other for some reason, convoluted wording for the "Cancel" button, a nonfunctional close button,...

**Comment by koeaw** [comment]
We agreed to split this in two to reduce complexity:

* the first/existing PR should solve the faulty model reference in the view and (if applicable) fix the reference to the entity in the template
* the other issues with the template (formatting, styling, tweaking of information displayed to users,...) should go into a second, independent PR

**Comment by b1rger** [comment]
Not exactly sure which of the two parts *this* issue relates to- according to the title probably the first. This would be great to have soon, as deleting an instance is a rather important feature (and its a small fix)

**Comment by koeaw** [comment]
Ah, right! Thx for the reminder.

I'll reduce #458 down to what's needed to fix the first obstacle (TempEntityClass).
