### ISSUE TITLE
Use verbose names for fields when available in the model

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#486]
In detail and edit views, use verbose names of fields when available. When a verbose name is not available, use the attribute name as the default value.

Thematically related to issue #102

**Comment by koeaw** [comment]
Related broader issue: #461 (primarily motivated by my shared concern/issue re: missing verbose names)

**Comment by b1rger** [comment]
Hm, at least in the detail view, the `verbose_name` of the field should be used:
https://github.com/acdh-oeaw/apis-core-rdf/blob/5e5a74fd48a3100632629096015e43a8bc30169e/apis_core/apis_entities/templates/apis_entities/detail_views/detail_generic.html#L115

**Comment by koeaw** [comment]
@gythaogg Are you perhaps referring to fields which originate in `TempEntityClass`? Those don't have verbose names set, but they are being phased out and should either get dropped or be replaced/worked around in your own `models.py`.

Or are you looking at an older version of Core?

I haven't yet transfered all field types for our project, so created a version of the app with the old models (feat. `TempEntityClass`) in a separate local branch so I can compare them while on the exact same setup (instance workflow + Core version). With the exception of the inherited fields, all verbose names seem to show up for me in both detail + edit view.

**Comment by koeaw** [comment]
... The one thing that doesn't work for me are the _labels_ (vs. values) for predefined `choices` in the detail view.

**Comment by b1rger** [comment]
> ... The one thing that doesn't work for me are the _labels_ (vs. values) for predefined `choices` in the detail view.

can you elaborate? I'm not sure what you mean

**Comment by koeaw** [comment]
> can you elaborate? I'm not sure what you mean

I think I should create a separate issue for this problem; have been meaning to anyway.

**Comment by b1rger** [comment]
I think this should be done by the merge of the new generic app in 45de48bea2b81823873066820a079635b8d7a04a - could you please check @gythaogg if this fixes the problem?

**Comment by b1rger** [comment]
> I think this should be done by the merge of the new generic app in [45de48b](https://github.com/acdh-oeaw/apis-core-rdf/commit/45de48bea2b81823873066820a079635b8d7a04a) - could you please check @gythaogg if this fixes the problem?

any news?

**Comment by b1rger** [comment]
ping?

**Comment by gythaogg** [comment]
Hi, can confirm that this fixes it in both edit and detail views. Thank you! Tested with apis-instance Discworld.
