### ISSUE TITLE
Make the default search option for text fields to be icontains instead of exact match

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#487]
In the search form where it is possible to enter values in individual attributes - I think it makes sense to keep exact match search as default for char and numeric fields, uri etc. but for large text fields maybe it might be useful if the default search method was icontains. Or use icontains for searching in all the fields.

**Comment by gythaogg** [comment]
Thanks to @b1rger https://django-filter.readthedocs.io/en/stable/guide/usage.html

**Comment by gythaogg** [comment]
apis_entities/filters.py seems to be overriding this setting for Char field - maybe we need to tinker with the settings here.

**Comment by b1rger** [comment]
With 45de48bea2b81823873066820a079635b8d7a04a the `apis_entities` app now uses `icontains` for search in `models.CharField` for AbstractEntities
