### ISSUE TITLE
Redesign edit entity view to clearly separate "Merge" from adding relations

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#488]
The Merge feature - which in Tibschol at least is not a frequently used feature - adding relations is a much more common usecase

It is slightly confusing to have the Merge link below "the Entity is related to" followed by the other entity types to which relations can be added.

![Image](https://github.com/acdh-oeaw/apis-core-rdf/assets/7236469/b8da81a9-ce65-4cf6-9b32-623b848487cc)

**Comment by gythaogg** [comment]
1. Swap the order of Merge with and the entity is related to
2. Change the text to Merge into
3. Make the merge explanation clearer
4. Make it clear that Merge with can expand a panel (like a expand_more icon)

**Comment by b1rger** [comment]
This was implemented in 45de48bea2b81823873066820a079635b8d7a04a
