### ISSUE TITLE
Decide on property reference type in triple model

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core-rdf#5]
Kinda related to https://github.com/acdh-oeaw/apis-core-rdf/issues/3

## Open points:

* Experiment with ways of using ContentType for Property classes themselves, rather than instances
* If we stick with property instances, their definition needs to be integrated into django's `migrate` command

## Description

Right now, properties are instantiated from one Property class, because on the django-side this is more intuitive and consistent with other usages, and also because it's easier. However it brings issues with migrations and modelling semantics.

E.g. here properties are instantiated in the tibschol project: https://github.com/acdh-oeaw/apis-ontologies/blob/e99f66d5a3290e01effa067736448316e92754c9/tibschol/models.py#L57

where the relation `Instance-Instance of->Work` is created like so:

```
    instanceOf = Property.objects.get_or_create(
        property_class_uri="http://id.loc.gov/ontologies/bibframe/instanceOf",
    )[0]
    instanceOf.name = "Instance of"
    instanceOf.name_reverse = "Instance of Work"
    instanceOf.subj_class.clear()
    instanceOf.obj_class.clear()
    instanceOf.subj_class.add(ContentType.objects.get(model=Instance.__name__))
    instanceOf.obj_class.add(ContentType.objects.get(model=Work.__name__))
    instanceOf.save()
    list_valid_properties.append(instanceOf)
```

This way, we can search for triples of one work and instances of it like so:

```
Triple.objects.filter(
prop=Property.objects.get(uri="http://id.loc.gov/ontologies/bibframe/instanceOf"),
obj=Work.objects.get(id=1)
)
```

Which is quite intuitive and usual within the django context.

## However, this has two downsides:

* Major downside: Since properties should reside in the ontology defintion, and since they are 'objects' of django models and not the 'django models' themselves, they are not registered under django's Migration logic. This means that changes in properties must be curated manually. That's why for now and in the tibschol project, I decided to identify properties with `instanceOf = Property.objects.get_or_create(property_class_uri=URI)` and then modify all of its attributes. This way the uri is the identifying attribute while others can change. Additionally all other properties not defined within this authoritative module are dropped when the surrounding function `construct_properties` is called. But this function call is currently done manually, and should be integrated ideally into django's `migrate` command - if possible.

* Minor downside: is that in the majority of RDF ontologies, we don't use instances of properties, but the classes themselves. My apis-rdf implementation breaks a bit with this pattern implicitely. Though this could be acceptable.

## Change it to ContentType

In django, the only way to refere to classes themselves in its ORM context, is to use their ContentType. I need to test this, however I am sceptical that the queries would look as smoothly as they do with the pattern of instantiang properties. E.g. it could look like so:

```
Triple.objects.filter(
prop=ContentType.objects.get(model_class_name="InstanceOf"), # or similiar
obj=Work.objects.get(id=1)
)
```

I am unsure how to encode needed attributes into ContentType such as name_reverse, and subj_class and obj_class. Further work is needed here.

## Conflict between three domains of meta and object:

In general, this is very tricky, because we have three meta<->object domains: 
* Django ORM (ContentType <-> model class)
* Python (class <-> object)
* Ontology (semantic human class <-> semantic human instance)

**Comment by steffres** [comment]
We will stick with properties being instances as this so much more pragmatic throughout the codebase. There are some downsides though which need compensational efffort as documented here: https://github.com/acdh-oeaw/apis-core-rdf/issues/59

**Comment by koeaw** [comment]
> But this function call is currently done manually, and should be integrated ideally into django's migrate command - if possible.

There's a new variable `CREATE_RELATIONSHIPS` which is checked for in `start.sh` to work around this, but it's not documented anywhere yet. See acdh-oeaw/apis-rdf-devops#38.

**Comment by steffres** [comment]
thanks for this context.
