### ISSUE TITLE
Remove the integration of fetching the metadata from external sources

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#50]
Some information is fetched from external sources. This source is not managed anymore, we should remove that integration.

**Comment by koeaw** [comment]
The fetching of project meta data is done/attempted here: https://github.com/acdh-oeaw/apis-rdf-devops/blob/main/webpage/utils.py#L24. `PROJECT_MD_URL` is put together manually at the top of the same file using `PROJECT_STATIC_URL`.

`PROJECT_DEFAULT_MD` sits here: https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis/settings/base.py#L55
