### ISSUE TITLE
add an ontology to the test setup

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#505]
currently we are testing apis_core without any ontology. Given that a lot of functionalities make only sense with an ontology in place we should test with one.

I can think of two options:
- clone the whole [discworld](https://github.com/acdh-oeaw/apis-instance-discworld) repo and symlink to the ontology. Would make it also possible to test overriding templates etc, but slower
- wget only the models file of the discworld repo. Only allows for model related tests, but would be faster

@b1rger any thoughts?

**Comment by b1rger** [comment]
We do now have an API endpoint to dump all the entities and their relations - we could `curl` that and the `models.py` from discworld *before* the tests run, put the files in the correct place and let Django do the rest

**Comment by sennierer** [comment]
currently we still use an empty database for testing

**Comment by b1rger** [comment]
we do now have an ontology since 69c8442fb0e831c373a197d7f599218ffed19b2c
