### ISSUE TITLE
confirm_delete.html template could use some work

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#518]
Follow-on to #485:

**Describe the bug**
The HTML of the [`confirm_delete.html` template](https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/core/templates/confirm_delete.html) is off:

* it effectively has two buttons, Confirm and Cancel, but does not place them next to each other as is typical
* the Cancel button does not look like a button and uses convoluted wording for no good reason
* the Confirm button also reads a bit awkwardly
* the close button of the modal ("x" in the upper right corner) is non-functional

**Screenshot:**
![Screenshot 2023-12-20 at 18-55-14 Title Placeholder](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/fda00617-56ce-484f-b47b-7079cc5ae8ea)

**Comment by b1rger** [comment]
I think the `No, bring me back` button should be removed altogether, the `Yes, I want to delete` button should simply say `Yes` and the `x` should be removed. It looks like this was meant to be a modal at some point, but its not, so maybe we should also replace the `modal` classes with `card` classes.
