### ISSUE TITLE
Deletion confirmation modal should show entity (verbose) name

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#519]
Follow-on to #485:

**Describe the bug**
The [`confirm_delete.html` template](https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/core/templates/confirm_delete.html) should display the entity class (verbose name) alongside the identifier of the object-to-be-deleted.

In our project, for example, objects share names across certain (related) entities, so being clear about what _kind_ of object is going to be deleted is important with regard to UX.

**Caveat / Heads-up**
The template is not _only_ used for confirming the deletion of entity objects but for instances of a couple other model classes as well.

**Comment by b1rger** [comment]
I think it would make sense for this to introduce a templatetag that extracts the enitity name from the model

**Comment by b1rger** [comment]
With the new `generic` implementation, it is now possible to override the `generic_confirm_delete.html` template on a per model basis - so you can create a `apis_ontology/person_confirm_delete.html` and and add additional information to the template.
Would this be a solution to this issue?

**Comment by b1rger** [comment]
The template was removed in 391f2dea9d0452e40efcc1f312497941c1ce99ff, because it was not used anymore. I'm therefore closing this
