### ISSUE TITLE
Allow groupings of entity fields in forms

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#53]
**Is your feature request related to a problem? Please describe.**
It'd be great if entity fields could be grouped together for better visual separation in forms for cases where there are _many_ of them (and some belong together thematically/logically). Right now, forms for entities with many fields are rather unwieldy. 

**Describe the solution you'd like**
We currently already differentiate between two sets of fields, see: https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/apis_entities/forms.py#L74 (note I renamed all relevant variables for clarity last I worked on this to use **main** vs. **meta**). These are displayed slightly differently on the front end. 

I'm guessing it should be possible to create more of these groups on the fly, and since we already check `APIS_ENTITIES`'s `form_order` setting anyway for ordering fields, I'm wondering if it couldn't be extended to allow for that as well.

**Additional context**
This is a feature request which should be considered when discussing the refactoring of entity settings (see e.g. acdh-oeaw/apis-ontologies#9) because it's related / could be implemented as an extension of the `form_order` setting.

**Comment by steffres** [comment]
I agree that we should do this, but see it as low priority. 

Let's postpone it until many more pressing issues are resolved.

**Comment by b1rger** [comment]
With the new generic app you can now override the default form with your own form.

This is an approach that is used in a downstream project, but you can do anything thats possible with [django-crispy-forms](https://django-crispy-forms.readthedocs.io)

```
from crispy_forms.layout import Layout, Column, Row
from apis_core.generic.forms import GenericModelForm
from crispy_forms.bootstrap import PrependedText
...

class LegacyStuffMixinForm(GenericModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        ...

        all_other_fields = [f for f in self.fields if f not in more_details]

        # lets combine some of the form elements that belong together
        # into rows in columns and use bootstraps PrependedText to replace
        # the label of the form fields
        if {"first_name", "name"} <= set(all_other_fields):
            all_other_fields.remove("name")
            all_other_fields.remove("first_name")
            row = Row(
                    Column(PrependedText("first_name", self.fields["first_name"].label)),
                    Column(PrependedText("name", self.fields["name"].label)))
            self.fields["first_name"].label = self.fields["name"].label = False
            all_other_fields.insert(0, row)

        self.helper.layout = Layout(*all_other_fields)
```
