### ISSUE TITLE
Problems with Django session

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#535]
**Describe the bug**
I'm (suddenly) having problems with my Django sessions, could this be related to dependencies? I've never run into this issue before and have a hard time pinpointing what it could be caused by.

It started with me having to reauthenticate/relog into my app _every single time_ my IDE auto-reloads on file changes, which is super annoying. The error that gets printed to the dev server console simply reads `Session data corrupted`.

The issue started yesterday sometime in the afternoon and there are two (related) things I'm thinking could potentially be responsible:
* I had an editable version of my own app show up with `pip freeze`, which I ended up removing because it was confusing `pip` (nothing bad, just annoying, related to custom Git/SSH settings) and because I hadn't intended it to be there,
* in the (drawn-out, thx to Poetry not being helpful) process, I discovered that my lock file wasn't up-to-date, so I updated it and realised that I'd previously not had some of the latest versions of dependencies installed, which I then installed.

Re: the first thing – I don't know how I ended up with it or how long it had been in editable mode, the thought here is more: maybe switching from one mode to the other (I reinstalled with `--no-root` again after) messed with the session in some way (leftover cached files or whatever?). I couldn't get rid of it with Poetry alone but also don't remember manually running `pip` (I really only use it for `pip freeze`ing). 

Looking for other clues to what could have caused it, I also came across mentions of JavaScript (which is how I discovered [the jQuery bug](#529)) as well as Gunicorn, but I didn't look into those further.

**Comment by b1rger** [comment]
> It started with me having to reauthenticate/relog into my app _every single time_ my IDE auto-reloads on file changes, which is super annoying.

This is probably due to https://github.com/acdh-oeaw/apis-acdhch-default-settings/commit/0f7e9e3d760104596c1f3b1bca950817c8ef1cce - you can simply set the environment variable SECRET_KEY=foo to stop that happening

**Comment by koeaw** [comment]
> This is probably due to [acdh-oeaw/apis-acdhch-default-settings@0f7e9e3](https://github.com/acdh-oeaw/apis-acdhch-default-settings/commit/0f7e9e3d760104596c1f3b1bca950817c8ef1cce) - you can simply set the environment variable SECRET_KEY=foo to stop that happening

Ahhh, thank you!!

**Comment by koeaw** [comment]
See, I think I got lazy with the `SECRET_KEY` variable because I knew we'd introduced `DEFAULT_SECRET_KEY` as fallback. :scream: I just checked my local settings (files) for the new app and sure enough couldn't find a `SECRET_KEY` variable anywhere (when I very def. set it for the old app...).

**Comment by b1rger** [comment]
Is there still an issue or has it been solved by adding the `SECRET_KEY`?

**Comment by koeaw** [comment]
> Is there still an issue or has it been solved by adding the `SECRET_KEY`?

Errmmm I've not yet fixed this on my end, gimme a few minutes...

**Comment by koeaw** [comment]
Fixed by setting `SECRET_KEY` in the local settings file(s) I use. Wanted it to be a proper one, though, so had to look up again how to generate it via this function that's included in Django ([get_random_secret_key()](https://github.com/django/django/blob/4879907223d70ee1a82474d9286ccfa5dae96971/django/core/management/utils.py#L79)).

Thx for the help, @b1rger!
