### ISSUE TITLE
create a JSON parser similar to the RDFParser already in place

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#539]
should allow to create entity entries according to a predefined configuration

**Comment by b1rger** [comment]
This can be implemented by inheriting from [GenericImporter](https://github.com/acdh-oeaw/apis-core-rdf/blob/6398ad8f902132c9bd5512626d0ded319b66d07d/apis_core/generic/importers.py#L7), which uses json by default to parse request answers. Overriding `mangle_data` should be enough to extract information from the response
