### ISSUE TITLE
Decide the concept for RootObject children

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#54]
_Originally posted by @steffres in https://github.com/acdh-oeaw/apis-core-rdf/issues/49#issuecomment-1449940934_

> RootObject will be the major "thing" for everything that exists in an ontology. However RootObject will also be used for Properties and Vocabularies / Concepts. So RootObject can't be assumed to stand for an entity, as a potential replacement.
> We will definitely need a simple elegant way to differentiate between "Entity", "Property", "Vocabulary/Concept" since they will all inherit from RootObject. Maybe boolean flags attached to dedicated Abstract Classes for each? But that's a separate issue.

So here is that separate issue.

I would propose to simply use inheritance. We could implement the classes `Entity`, `Property`, `Vocabulary` that inherit from `RootObject`. I'm not sure what value an additional boolean flag would add - could you explain the idea behind that?

**Comment by steffres** [comment]
Actually I did mean to use inheritance: 

> attached to dedicated Abstract Classes for each

I think for these three we could have three abstract classes: `AbstractEntity`, `AbstractProperty`, `AbstractVocabulary`. And by "abstract" I also mean in Django's context, i.e. not persisted on DB to avoid joins since we already have so many of those. But in the python runtime they would still be proper parent classes nevertheless.

An advantage of boolean flags like `is_entity=true` for example would just be convenient to query for the type, as any child class / instance would have this directly attached. The alternative to climb up recursively the path of parent classes to find a certain base class seems quite cumbersome in comparison, especially given that we need to do this very often throughout the codebase.

**Comment by b1rger** [comment]
> An advantage of boolean flags like `is_entity=true` for example would just be convenient to query for the type, as any child class / instance would have this directly attached. The alternative to climb up recursively the path of parent classes to find a certain base class seems quite cumbersome in comparison, especially given that we need to do this very often throughout the codebase.

I'm not sure if a boolean flag is more convenient than `isinstance`.
On the contrary: If we only set the boolean flag in the abstract classes, we would have to except for example `AttributeError: 'AbstractEntity' object has no attribute 'is_property'`. The alternative would be to set *all* the boolean flags in the `RootObject` to False, which means for every additional child class we introduce we would have to add a boolean attribute.

```
class Person(AbstractEntity):
    pass

foo = Person()
print(isinstance(foo, AbstractEntity))
```

**Comment by steffres** [comment]
`isinstance` however has the disadvantage of working only on the instance level. But often we also need to differentiate classes themselves. 

A boolean flag attached to the class has the benefit of being available both on the instance as well as the class itself.

And yes, I imagined it like you outlined, like so:
```
class RootObject:
    is_entity = False
    is_property = False
    is_vocabulary = False
    
class AbstractEntity(RootObject):
    is_entity = True
    
class AbstractProperty(RootObject):
    is_property = True
    
class AbstractVocabulary(RootObject):
    is_vocabulary = True
```

**Comment by b1rger** [comment]
> `isinstance` however has the disadvantage of working only on the instance level. But often we also need to differentiate classes themselves.

Doesn't simply comparing (i.e. `print(AbstractProperty is AbstractEntity)`) work in that case?
Sorry if me questioning this approach is annoying, but I fail to see the concrete usecase and adding properties for children to the parent classe makes the app really unflexible. Lets say we create a separate app that introduces `class AbstractSomething(RootObject)` - should we than add a `is_something` property to `RootObject`?

**Comment by steffres** [comment]
I don't think that adding boolean flags would make the app that much inflexible. 

But if it can be avoided, it's better to do so. And actually I just looked for it and found `issubclass` which works on the class level and with arbitrary classes in between a given inheritance tree. 

Then we could use `isinstance` for instances and `issubclass` for classes.

A potential downside of this though might be that we would always need to import the respective base classes. Occasionally though I have stumpled into circular import loops (module A imports from module B which imports from A). I could avoid them by untangling the imports, but it might be that we would run into this problem with this approach. 

But anyway, I don't have a strong preference. I see both, the boolean flags, as well as `isinstance` and `issubclass`, as viable and minimalistic. And actually I do prefer the latter as it means slightly less code.

**Comment by steffres** [comment]
I implemented it with `isinstance` and `issubclass` as it is more minimalistic and without the overhead of crawling through inheritance trees as I originally had anticipated. 

No need for boolean flags.

Was implemented here: https://github.com/acdh-oeaw/apis-core-rdf/issues/70
