### ISSUE TITLE
allow apis-rdf instances to query entities from other instances and import objects

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#540]
to work this probably needs:

- [x] #539

**Comment by b1rger** [comment]
Can we be more specific whats expected here?

**Comment by sennierer** [comment]
the code to do this is already there. We can overwrite the `mangle_data` function of the `GenericImporter` class to map fields to fields. So this connection needs to be set up in the apis-instances. Thus closing this issue here.
