### ISSUE TITLE
Property URIs aren't implemented 

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#57]
**Describe the problem**
Class `Property` has a field `property_class_uri`, which is unused.

It's created here: https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis_core/apis_relations/models.py#L69 but never assigned a value, and remains empty in the database table that holds the rest of the info for property objects.

**Expected behavior**
I can only guess at its intended purpose, but assume it was meant to be used to access/list triples by relationship, similar to how each entity can be accessed individually.

Currently, only the underlying properties, or the full list of triples can be accessed via the main menu (via `Relations > Property` and `Relations > Triples`, respectively), but not groups of triples.

**Additional context**
It's unclear if this has just been sitting unimplemented or if this is a leftover of an abandoned idea.

**Comment by steffres** [comment]
The reasoning for `property_class_uri` is that each property instance can have a single URI assigned, as is defined within RDF. (e.g. https://www.w3.org/1999/02/22-rdf-syntax-ns#type ).

Though it might never be used anyway because of the current URI implementation being a separate model class.
