### ISSUE TITLE
Implement structural management of property's history / ontology integration / migration

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#59]
We will very likely stick with "semantic properties" being instances of "Property" django mode class, as this integrates better throughout the codebase. 

However them being instances has some major open issues:
* they are not picked up by migrations
* their relations to entity classes (which ones are allowed as subject / object?) is not tightly integrated.
* how to control for modifications of them? 

We need to find solutions for each of them. For now however something like this works:

```
person_has_place_of_birth = Property.objects.get_or_create(
    name="has place of birth",
    name_reverse="is place of birth of",
)[0]
person_has_place_of_birth.subj_class.clear()
person_has_place_of_birth.subj_class.add(ContentType.objects.get(model=Person.__name__))
person_has_place_of_birth.obj_class.clear()
person_has_place_of_birth.obj_class.add(ContentType.objects.get(model=Place.__name__))
```

But it's very fragile. 

Ideally we find a custom logic that is nicely reusable acros projects and histories of them, and also which hooks into django migrations too.

**Comment by koeaw** [comment]
It's been a while but I'm currently once again faced with the problem of having to modify our properties in ways that go beyond adding/removing entity classes, so wanted to surface this issue for discussion at the JF, hence  -> https://github.com/acdh-oeaw/apis-core-rdf/labels/needs-attention.

**Comment by sennierer** [comment]
this will be solved with new relations implementation
