### ISSUE TITLE
Date parsing/conversion

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#615]
We need to introduce a date parsing mechanism to our project because some incoming date data does not (have to) follow strict formatting rules.

Given that the current [`DateParser.py`](https://github.com/acdh-oeaw/apis-core-rdf/blob/44e1cf128aab9b214f245da7019e74a4f7ec2490/apis_core/utils/DateParser.py) code is old and convoluted – see also PR #125, which sadly didn't make it into the code base – should we continue to use this or is there a better solution?

We don't need _very_ fancy date parsing, meaning we're currently only dealing with dates from the 20th century to now and incoming dates won't contain vague textual descriptions (e.g. "approx. 20-30 years B.C.") but will be number-based and use date formats/variations commonly used in AT (+ maybe ISO format). Examples: 1.5.1970, 02.04.85, 23/12/1999, 2024-01-01.

**Comment by b1rger** [comment]
I guess the date should be stored in a field and the original input string can be thrown away? You can use `DateParser.py`, but you might have better luck with [dateparser](https://dateparser.readthedocs.io/en/latest/)

The advantage of `DateParser.py` is, that it calculates timespans of date (i.e. if you only know the year of a date), but that does not seem to be needed in this case

**Comment by koeaw** [comment]
> I guess the date should be stored in a field and the original input string can be thrown away? 

Almost! We're planning to keep the original input strings around and editable by content managers and further updates/corrections to them should get propagated to the (non-editable) field for the streamlined date.

Hmm, we don't need to handle _time spans_ per se, but ah, should have clarified above that we indeed will also have to deal with year-only dates. I'll look at dateparser to see if it can handle incomplete dates as well, thank you!

**Comment by koeaw** [comment]
> I'll look at dateparser to see if it can handle incomplete dates as well, thank you!

Yup, seems to be the case: https://dateparser.readthedocs.io/en/latest/introduction.html

**Comment by koeaw** [comment]
Closing this as the question was answered. Thx, @b1rger!
