### ISSUE TITLE
Investigate into DB caching

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core-rdf#63]
**Ideally through work invested here, we can carry solutions over to other apis instance too. Coupled with high performance gains makes this a high priority issue.**

In Jelinek we experience performance issues with join-heavy reads by the complex serializers. There is no way around a high query-complexity, so we need to look into optimizing the DB reads. There are multiple paths to approach and we prioritize them like this by ease of integration:

* Django caching

Look into how Django provides APIs / settings for highest ease of use and outsourcing the complexity of caching onto Django. It must be a popular issue / use-case after all. With this approach we try to modify SQL technicalities as little as possible.

https://docs.djangoproject.com/en/4.1/topics/cache/#database-caching

* SQL native caching

Look into how engines provide caching. Especially in regards to materialized views / prepared statements (though MySQL does not support materialized views, while PostgreSQL does). Of course we should avoid writing / modifying SQL statemens as mach as possible to avoid potential interference with Django's ORM.

Ideally such caches are generated by the engine itself. If manual creation is needed, we need to consider benefits / costs. 

* External caching with search-index providers (Solr, Typesense)

Has been used before in various projects, so there is institutional knowledge. However we should try to avoid this approach in favor of SQL native ones, as we should avoid adding a full component into our stack entailing various integration efforts. Hence we will take this option only if the others above are exhausted.

**Comment by sennierer** [comment]
given that this is project specific this should be decided per project, closing it here
