### ISSUE TITLE
Adapt REST API additional serializers so that they can have multiple root model classes

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#65]
We can load arbitrary additional REST serializers by providing them a custom path structure.

The logic for creating them is here: https://github.com/acdh-oeaw/apis-core-rdf/blob/768e652b717a393b2e599bf30abf37cd9503a1c2/apis_core/api_routers.py#L602

Example path structures can be seen here: https://github.com/acdh-oeaw/apis-ontologies/blob/68fb0737452f950e9c7cfd4f75ed7f02df2a6ba2/jelinek/additional_serializers.py#L17

This works by utilizing Django-rest-api's ModelSerializer ( https://www.django-rest-framework.org/api-guide/serializers/#modelserializer ), and works flawlessly with arbitrary nested structure, **but has the disadvantage that each Serializer has exactly one root model class only.** 

It would be useful if we could define arbitrary root model classes like for example so:
```
        path_structure={
            Chapter: [
                Chapter.id,
                Chapter.name,
                Chapter.chapter_number,
            ],
            F1_Work: [
                F1_Work.id,
                F1_Work.name,
            ]
        }
```

Maybe this can be solved by using the general Serializer ( https://www.django-rest-framework.org/api-guide/serializers/#serializers ) instead of the ModelSerializer?

### where to look into

The ModelSerializer class is dynamically created for each path structure here: https://github.com/acdh-oeaw/apis-core-rdf/blob/768e652b717a393b2e599bf30abf37cd9503a1c2/apis_core/api_routers.py#L671

And the model class is passed to it here: https://github.com/acdh-oeaw/apis-core-rdf/blob/768e652b717a393b2e599bf30abf37cd9503a1c2/apis_core/api_routers.py#L678

**Comment by b1rger** [comment]
`additional_serializers` has been dropped in 190e5f3f95b1fd2d7351e6807e27e3acdafd7d80
