### ISSUE TITLE
Create a DateMixin

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#66]
As discussed in the JFX, we want to introduce Mixins. Therefore we chose to
implement a *simple* Mixin that could replace the date related functionality fo
TempEntity. This should probably wait until the big RDF refactoring is merged.

**Comment by steffres** [comment]
Thanks for creating this issue. Yes, we should introduce it once `TempEntityClass` has been removed, that's the major clashing point. But this will be done very soon. So experimentational work on Mixins can still continue in parallel.

**Comment by gregorpirgie** [comment]
- [link zu mixin playground repo](https://github.com/acdh-oeaw/django_mixins_playground
