### ISSUE TITLE
JavaScript / jQuery code needs cleaning up

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#672]
Our code is full of incorrect JS comparisons and outdated variable declarations. [This function declaration](https://github.com/acdh-oeaw/apis-core-rdf/blob/v0.13.1/apis_core/apis_entities/templates/apis_entities/apis_templatetag.html#L42-L56) alone contains several instances of both.

Excerpt (example for both):
```js
if (document.cookie && document.cookie != '') {
    var cookies = document.cookie.split(';');
...
}
```

Should be:
```js
if (document.cookie && document.cookie !== '') {
    let cookies = document.cookie.split(';');
...
}
```

That first check `if (document.cookie)` seems nonsensical either way, looks like Python transferred to JS. Unless that's special jQuery magic I'm not aware of (which is entirely possible, as I've never written any jQuery myself).

**Comment by b1rger** [comment]
Can we make this a little bit more specific? Is there some linting that we can use so it is clear what "clean" and "not clean" means? If we can not check if an issue has been solved, it will just hang here forever...

**Comment by richardhadden** [comment]
What's wrong with this, apart from somewhat passé use of `var` instead of `let`?

(The ` if(document.cookie ...)` is required, as no cookies being set returns `undefined`, not empty string)

**Comment by koeaw** [comment]
Relevant docs: [Equality comparisons and sameness](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness), [typeof operator and undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#typeof_operator_and_undefined).

**Comment by koeaw** [comment]
> `document.cookie` isn't a variable

Fair enough.

We both interpreted its intent to be to check for `undefined` cookies, in any case. And I'd argue there are better/more precise ways to check for undefined properties of objects as well. But ehh, looks like `document.cookie` isn't even a data property. :stuck_out_tongue_winking_eye:

And yeah, looks like it never does not exist in major browsers. I didn't even look at what the cookie does, so not sure if we even still need that check at all. The last cookie-related code I encountered was for the now-removed toggle between view/edit mode for entities, which is the kind of setting I'd use `localStorage` for, not cookies.

**Comment by b1rger** [comment]
Just for context: the code is apparently coming from this stackoverflow post: https://stackoverflow.com/a/23350233

It is used in the relations javascript to set the CSRF token for ajax form of the relations

**Comment by koeaw** [comment]
> Just for context: the code is apparently coming from this stackoverflow post: https://stackoverflow.com/a/23350233

Interesting... especially considering content posted on SO is [creative commons-licensed](https://stackoverflow.com/legal/terms-of-service/public#licensing) ("Subscriber Content" subsection).

**Comment by koeaw** [comment]
> And the relevance of this in this context is..?

Time spent discussing random copy-pasta feels like time wasted, to me. If the whole snippet was lifted from somewhere else, it's a bit pointless to discuss individual problems with it because the answer could simply be "laziness". Proper attribution would have made this clear right away.

Additionally, my assumption now is this probably wasn't a one-off thing. Which makes unknown n% of the remaining code equally kind of pointless to discuss with regard to style etc. And also doesn't make me feel too confident about other things.

**Comment by b1rger** [comment]
> Can we make this a little bit more specific? Is there some linting that we can use so it is clear what "clean" and "not clean" means? If we can not check if an issue has been solved, it will just hang here forever...

q.e.d

**Comment by sennierer** [comment]
move all JS functions in dedicated *.js files in the static directory and run JS linters on these files:
- [ ] move all JS functions to JS files (in static directory)
- [ ] decide on a JS linter and run it on the code
- [ ] add the linter to the GH actions workflow

**Comment by b1rger** [comment]
> move all JS functions in dedicated *.js files in the static directory and run JS linters on these files:
> 
>     * [ ]  move all JS functions to JS files (in static directory) ... [Refactor JavaScript inclusion #1277](https://github.com/acdh-oeaw/apis-core-rdf/pull/1277)
> 
>     * [ ]  decide on a JS linter and run it on the code
> 
>     * [ ]  add the linter to the GH actions workflow

all those tasks have been implemented
