### ISSUE TITLE
django-tables2 "LinkColumn" is deprecated

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#676]
I've been seeing Django Tables2's `LinkColumn` around in our code, which is being phased out/[deprecated](https://django-tables2.readthedocs.io/en/latest/pages/api-reference.html#linkcolumn):

> This column should not be used anymore, the `linkify` keyword argument to regular columns can be used to achieve the same results.

Just wanted to make a note of it in case it's still there.

(I'm still on version `v0.13.1` and haven't checked beyond that.)

**Comment by b1rger** [comment]
```
grep -r LinkColumn *
apis_core/apis_metainfo/tables.py:    id = tables.LinkColumn()
apis_core/apis_relations/tables.py:                self.base_columns["other_entity"] = tables.LinkColumn(
apis_core/apis_relations/tables.py:                self.base_columns["other_entity"] = tables.LinkColumn(
```

**Comment by b1rger** [comment]
But its still part of django-tables2 and there is nothing broken so far in our codebase, so I'm removing the `bug` label

**Comment by koeaw** [comment]
True!

**Comment by koeaw** [comment]
I'm leaving a snippet for `Column` here, for reference:

```py
    my_field = tables.Column(
        orderable=True,
        linkify={
            "viewname": "apis:generic:update",
            "args": [A("self_contenttype"), A("pk")],
        },
        empty_values=[None],
    )
```
I've previously used this as replacement (but am currently looking into `TemplateColumn` instead).
