### ISSUE TITLE
Weird action elements placement in edit views

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#683]
My `update` views all look like this at the top:

![Screenshot 2024-02-29 at 17-36-30 Ein Werk](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/75357bb4-8bb7-4d60-a7ae-2934f060da47)

...  using generic app (URL is `/apis_ontology.work/update/X`).

Is this intentional? A bug on my end? Potentially already fixed in a newer version? It's not super high priority and I could look into fixing this.

I generally wanted to suggest to turn the action buttons into actual buttons, which is why I already looked at the CSS for _a bit_ a while ago. (Not for this template, but for list view; stopped short at this one.)

**Comment by koeaw** [comment]
Ah, hmm, is it possible that my templates contain a mix of things while I'm not yet done implementing everything necessary for the switch to generic app?

I just noticed that I'm also seeing the buttons in (generic) detail view, including the "view" button (!), which links to the _old_ "detail" view. :thinking:

**Comment by b1rger** [comment]
> Is this intentional?

I'm not really sure if I'm missing something, but the edit and updated views were redesigned during the switch to the generic app (well, actually, replaced, not redesigned). I'm not seeing anything wrong in the screenshot, but maybe I'm missing what exactly you are referring to

**Comment by koeaw** [comment]
It's the placement I'm primarily having an issue with.

They are not visually grouped with the entity type + name. They sit on their own line, very far apart, a couple on the far left, the others hidden in a dropdown in a non-obvious way. (I only discovered them when I couldn't "see" them but knew they had to be there.)

The grouping of icon + icon label looks off as well. And is inconsistent with how the buttons look in e.g. the table view.

Old version for comparison:
![Screenshot 2024-02-29 at 18-46-58 Alles Wolken (ID 639)](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/154a4c5e-0236-4a93-8fbf-39777e2fd743)

Don't get me wrong, the previous placement wasn't great either, nor were those separators.

I started working on improving the old version at some point, maybe I still have the WIP branch around. It was mostly focussed on placement, probably about `flex`ing that entire header part of the page, which might potentially make it reusable for the new version, at least in parts.

**Comment by b1rger** [comment]
> They are not visually grouped with the entity type + name

Yes. Should they?

> They sit on their own line, very far apart, a couple on the far left, the others hidden in a dropdown on the far right in a non-obvious way.

Yes, those are two different menus. Primary and secondary actions, so to say. The primary menu uses [bootstraps card navigation](https://getbootstrap.com/docs/4.0/components/card/#navigation) and list two views that use a similar layout , the secondary uses a navbar menu and lists actions that move the interaction to different pages *and* it provides a way to add additional actions. It is similar to the comment box I'm using to write this comment - "Write" and "Preview" at the left, a lot of other actions at the right.

**Comment by sennierer** [comment]
given that @koeaw doesnt have time to refactor that currently, we close this for now
