### ISSUE TITLE
Refactor generic app action buttons so "duplicate" button gets added last

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#694]
I've commented on this in the old version as well -> if there is an established order of UI elements, that order shouldn't be upset by moving elements around when something gets added/removed.

If view-edit-delete is the default and duplicate is an add-on to that, it should get added at the end (of the list, table, etc.).

(The idea was perhaps to order by "severity", which might make sense in a 4-button-setup, but even in that scenario I could think of advantages of putting the duplicate button last.)

**Comment by b1rger** [comment]
(Just to be sure- you're referring to the buttons in the table of the list views?)
![Screenshot-2024-03-04-150913](https://github.com/acdh-oeaw/apis-core-rdf/assets/1143280/53da2c13-6df0-4fb0-af43-833238dd88cf)
This is how it looks in my test setup. Is this what you're referring to? Is it not the last button in your setup?

**Comment by b1rger** [comment]
> This is how it looks in my test setup.

ah, I see now - that was a configuration setting on my side. It seems to come before the delete button by default

**Comment by koeaw** [comment]
Btw. is there a reason why the duplicate button is not called "duplicate" but "noduplicate"? That seems a bit unintuitive to me.

**Comment by b1rger** [comment]
> Btw. is there a reason why the duplicate button is not called "duplicate" but "noduplicate"? That seems a bit unintuitive to me.

Yes, because when you define a Column thats called like a function of the element it refers to, it calls that elements function. I found out the hard way and had suddenly a lot of duplicates ;)
(The change in d5cfdb55cb005d3967bfd04aad7130526225d93b does prevent this, but additionally simply calling it `noduplicate` instead of `duplicate` seemed safer)
