### ISSUE TITLE
Make Texts Attribute Again

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#7]
In vanilla, texts (long elaborate human texts, not only character fields) are model classes that are linked to entities. It was designed like this out of necessity because the entities in vanilla were inflexible and various projects needed various different texts for entities like works.

In the rdf architecture I propose to remove this design and attach texts as attributes to entities directly, because assuming either possible requirements:

requirement A: given an ontology where a text is an attribute of an entity (or somewhat closely dependent), this would be better reflected by designing texts as attributes in the respective apis-ontology.

requirement B: given an ontology where a text is an independent entity, this can be equivally well reflected in an apis-ontology, where we would just define a model class that only has a text as attribute and the model class acts as its carrier.

Since both requirements can be fullfilled by attaching texts as attributes I see no benefit in keeping it the vanilla way.

Additionally within vanilla a text-type is an instance of a model class TextType. However semantically a text-type is rather a class, hence this design creates semantic frictions.

If we attach texts as attributes to entities, this would have side-effects on the apis-highlighter module as it is wired onto the current Text model classes. However the resulting refactoring should be of acceptable work-load.

**Comment by steffres** [comment]
This could touch upon highlighter refactoring: https://github.com/acdh-oeaw/apis-core-rdf/issues/75

**Comment by steffres** [comment]
Relevant `TODO` in code: https://github.com/acdh-oeaw/apis-core-rdf/blob/eb0d4bc80635d55e9ba7aa000ff614a0759c0f3a/apis_core/apis_metainfo/models.py#L417

**Comment by b1rger** [comment]
`Text` has been removed, `highlighter` has been replaced by `highlighter-ng`, ontologies can now put custom non enitity models in their `models.py`...

I'm therefore closing this
