### ISSUE TITLE
Add cardinality to Property (especially for reifications)

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#71]
It would be very useful if properties can have cardinalities defined with regard to their subj / obj classes. 

E.g. `mother of` should be possible to only attach once between two persons.

But foremost it would be useful in de-cluttering the reification form interface, as it provides possibility to attach multiple related entities to it, including relations back to the entity class you are currently editing in.

E.g. If you are in a person edit view and you have a reification which you want to only relate to a place, then the reification form would also load the possibility to attach other persons to it, because it's within the valid property range. It's ugly but it works as intented.

If we could restrict this with cardinality on a property it could remove quite some visual noice of the reification forms, also lower displaying the 'add new relation' and 'remove relation' button there too.

**Comment by sennierer** [comment]
given that we will move to another relation implementation closing this for now
