### ISSUE TITLE
django-tables2 sequences placeholder

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#715]
We use the django-tables2 `"..."` placeholder for sequences in [`AbstractEntityTable` here](https://github.com/acdh-oeaw/apis-core-rdf/blob/60b2df68aeea4052f3f47edd9fff493480b9193a/apis_core/apis_entities/tables.py#L16-L17) – can it be removed?

Problem is that `"..."` cannot be used in custom tables when inheriting from `AbstractEntityTable.Meta.sequence` (because the placeholder cannot be used twice). Plus, it forces all other fields to go before the columns for the action buttons, so one could not e.g. decide to place a field after the buttons without duplicating it.

The placeholder also gets used in [`GenericTable`](https://github.com/acdh-oeaw/apis-core-rdf/blob/60b2df68aeea4052f3f47edd9fff493480b9193a/apis_core/generic/tables.py#L85-L87), where it doesn't seem to serve a _real_ purpose either – the only field that gets inserted is `desc`, which could be written out instead – but it doesn't get in the way as long as no-one tries to inherit from `GenericTable`'s `sequence` directly.

It seems like generally, the placeholder should be avoided in sequences which might get inherited so users can still make use of it in their own custom configs. 

Edit: The django-tables2 docs actually mention the placeholder can only be used once, see `sequence` section in [`Table.Meta`](https://django-tables2.readthedocs.io/en/latest/pages/api-reference.html#Table.Meta).

**Comment by b1rger** [comment]
> Problem is that `"..."` cannot be used in custom tables when inheriting from `AbstractEntityTable.Meta.sequence` (because the placeholder cannot be used twice). 

What do you mean by "cannot be used in custom tables"? Is there an error message?

If I use `sequence = ('name', 'first_name', 'start_date', 'end_date', '...', 'name')` in a Table whose Meta inherits from `AbstractEntity.Meta` it creates the columns exactly as defined in th sequence

> Plus, it forces all other fields to go before the columns for the action buttons, so one could not e.g. decide to place a field after the buttons without duplicating it.

Without duplicating what?

> The placeholder also gets used in [`GenericTable`](https://github.com/acdh-oeaw/apis-core-rdf/blob/60b2df68aeea4052f3f47edd9fff493480b9193a/apis_core/generic/tables.py#L85-L87), where it doesn't seem to serve a _real_ purpose either – the only field that gets inserted is `desc`, which could be written out instead – but it doesn't get in the way as long as no-one tries to inherit from `GenericTable`'s `sequence` directly.

All the fields of childclasses get added before the action buttons, not only `desc`. `desc` is the only field defined in the `GenericTable` but if I add additional fields in a child table, they come before the action buttons in the sequence, too.


> Edit: The django-tables2 docs actually mention the placeholder can only be used once, see `sequence` section in [`Table.Meta`](https://django-tables2.readthedocs.io/en/latest/pages/api-reference.html#Table.Meta).

Once **per sequence**, not once in the inheritance chain. I.e. you can not write `sequence = ('name', '...', 'first_name', '...')`

**Comment by koeaw** [comment]
> Once **per sequence**, not once in the inheritance chain. I.e. you can not write `sequence = ('name', '...', 'first_name', '...')`

What's meant by "inheritance chain" here? If I want to inherit from a `sequence` further up in the hierarchy and add my own fields, I have to add them to the existing, inherited sequence in my entity class's `Meta` class.

What I'm doing is:

 ```py
class ArchiveTable(AbstractEntityTable, tables.Table):
    id = tables.Column()

    class Meta(AbstractEntityTable.Meta):
        exclude = ["desc"]
        sequence = ("...", "id") + AbstractEntityTable.Meta.sequence
```

Which results in:

```
ValueError at /apis/entities/entity/archive/list/

'...' must be used at most once in a sequence.
```

How else am I supposed to inherit those attributes?

**Comment by koeaw** [comment]
Basically what I'm trying to do is build my own `BaseEntityTable`, which is supposed to consist of the buttons from `AbstractEntityTable`  + some fields shared across tables. Other tables are meant to inherit from it (and its `Meta`) so I don't have to repeat the same stuff in every table.

**Comment by koeaw** [comment]
> If I use `sequence = ('name', 'first_name', 'start_date', 'end_date', '...', 'name')` in a Table whose Meta inherits from `AbstractEntity.Meta` it creates the columns exactly as defined in th sequence

What does "it creates the columns exactly as defined in th sequence" mean here?

You get all the _columns_ defined in `AbstractEntityTable` – including `Desc` if you don't filter it out via `exclude` – but the `"..."` in your sequence doesn't replicate `AbstractEntityTable`'s `sequence`.

**Comment by b1rger** [comment]
This:
```
sequence = ("...", "id") + AbstractEntityTable.Meta.sequence
```
is not inheritance. You're simply accessing an attribute of `AbstractEntityTable.Meta`. That it happens in a class that inherits from `AbstractEntityTable.Meta` is just coincidence. You could as well write:
```
sequence = ("...", "id") + ("...", "view", "edit", "delete", "noduplicate")
```
and then you see the problem: there are two `...` in the sequence. So simply write:
```
sequence = ("...", "id", "view", "edit", "delete", "noduplicate")
```

The wording "when inheriting from `AbstractEntityTable.Meta.sequence`" through me off here, because you don't *inherit* from `AbstractEntityTable.Meta.sequence`

**Comment by koeaw** [comment]
The point is that I want to build on the existing sequence.

I thought my `Meta` class had to inherit from the parent table's `Meta` class in the first place before I could do anything with it. Okay, so maybe that's not the case.

But in the example you gave:

```py
sequence = ("...", "id", "view", "edit", "delete", "noduplicate")
```
you aren't inheriting from the parent table's `Meta` either. You are just defining a new `sequence` for the child table from scratch. No? In this example, the placeholder just adds all fields/columns for this table, including any inherited table columns, all fields from this table's model, as well as columns defined on the child table.

For this to work, I don't need to reference the parent's `Meta` at all, would I.

---

The thing I want to do, though, is _not to have to spell out_:
```py
sequence = ("MY_FIELD_1", "MY_FIELD_2", "view", "edit", "delete", "noduplicate", "MY_FIELD_3")
```
_for every single child table_. I want to reuse sequences. I want to define them once, in a parent table, and then reuse them as-is in child tables. Not just `AbstractEntityTable`'s either, but `sequences` from other parent tables as well.

**Comment by koeaw** [comment]
Ok, so I guess there is a conflict of interests here, and maybe we should discuss this at the JF.

**Comment by b1rger** [comment]
> I want to define them once, in a parent table, and then reuse them as-is in child tables.

I still don't get what prevents you from doing that, but yeah, lets discuss this in person

**Comment by sennierer** [comment]
given that removing `...` from the sequence would mean that every user has to add a sequence to generic tables we will stick with the current implementation (`...` used in sequence of generic table.
