### ISSUE TITLE
Protect our branches

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#72]
We should discuss protecting our branches. I would propose to lock down `dev` and make pull requests required. Good would also be to make successful tests required. I don't think that requiring a review makes any sense, though.

Documentation on branch protection can be found on: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by steffres** [comment]
I fully agree on branch protection and making tests required.

We have been too sloppy in this regard.

For PRs, perhaps, but what's the reasoning? best-practice? I'm more sceptical on this because what's the point in making them mandatory if reviews are not required? Is a PR without a review even a PR conceptually? 

On the other hand, being able to either do a PR or a push straight to a branch, already inherently communicates its organizational intention.

**Comment by b1rger** [comment]
> For PRs, perhaps, but what's the reasoning? best-practice? I'm more sceptical on this because what's the point in making them mandatory if reviews are not required? Is a PR without a review even a PR conceptually?

It enhances visibility of the changes.
The changes can be discussed via comments below the PR.
The changes can be reviewed, even if you don't *require* them to be reviewed.
It makes it possible to distinguish between stuff thats being worked on (*draft*) and stuff that basically ready to be reviewed from the POV of the developer. If there is only a branch, I don't have any idea if a review makes sense at any point in time (another option would be to name branchs `wip/` and rename it when it is ready to be reviewed but given we already use some github workflows, it probably makes sense to stick with it).
We can use labels for PRs

> 
> On the other hand, being able to either do a PR or a push straight to a branch, already inherently communicates its organizational intention.

I'm not sure what you mean by that. What is *doing a PR straight to a branch*?

I would say a *branch* is a technical concept, a *PR* is the social concept to make collaboration possible. In other projects the social concept is a patch email that is being discussed, but it is still based on a *branch*

**Comment by koeaw** [comment]
PRs also allow the running of actions, which is useful because we'll want to make sure we don't reintroduce bad formatting now that we've run Black on the entire repo(/project?).

**Comment by b1rger** [comment]
> PRs also allow the running of actions, which is useful because we'll want to make sure we don't reintroduce bad formatting now that we've run Black on the entire repo(/project?).

actions can also be triggered by pushes to a branch (and they are): https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Comment by koeaw** [comment]
> actions can also be triggered by pushes to a branch (and they are)

I wasn't aware we're running the formatter on every push, huh. Does this prevent merging of branches with failed actions? Or what exactly is the point of doing this?

In my mind, this isn't useful, but I also consider branches more temporary storage for "personal use" until they are ready to be merged (which a PR basically helps to "announce") and thus (force) push like nobody's watching. :p On GitLab, I pushed using the flag to skip CI/CD actions by default to not waste resources, but GitHub unfortunately doesn't support those. (But then, I don't know if there's a limit on GitHub actions with our organization account.)

**Comment by b1rger** [comment]
> > actions can also be triggered by pushes to a branch (and they are)
> 
> I wasn't aware we're running the formatter on every push, huh. Does this prevent merging of branches with failed actions? Or what exactly is the point of doing this?

Well, given we don't have branch protection rules yet, so there are pushes to main or other branches that should be tested.

> 
> In my mind, this isn't useful, but I also consider branches more temporary storage for "personal use" until they are ready to be merged (which a PR basically helps to "announce") and thus (force) push like nobody's watching. :p On GitLab, I pushed using the flag to skip CI/CD actions by default to not waste resources, but GitHub unfortunately doesn't support those. (But then, I don't know if there's a limit on GitHub actions with our organization account.)

https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by koeaw** [comment]
> Well, given we don't have branch protection rules yet, so there are pushes to main or other branches that should be tested.

Fair.

I'm aware of keyword-based skipping of actions but don't find it helpful for my workflow (and think it "pollutes" commit messages).

**Comment by b1rger** [comment]
> `main` should equally be locked, and only accept merges from `dev`, and, idk, `hotfix` branches, probably? Though the latter would require a mechanism to check the next merge from `dev` contains any preceding hotfix commits as well.

I'd be happy if we start with a basic branch protection that requires Pull Requests. Given that we have *no* rules regarding pushes, this would already be a big step. As soon as everyone is used to doing PRs, we can get to the next step.

> ETA: If I'm understanding correctly, a **Strict** setting for [Require status checks before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging) is the kind of mechanism I was thinking of.

See above. In my experience, this setup needs **a lot of work**(!) regarding the CI setup and the test cases, otherwise it leads to trouble, because of misconfigured failing tests that prevent important commits from being merged. I think we should keep the setting in mind and reevaluate it once both the test setup and the CI is managed by more than one person.

**Comment by koeaw** [comment]
Fair.
