### ISSUE TITLE
Adapt highlighter to new ajax logic, remove old ajax entirely

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#75]
Old scattered ajax logic is to be fully replaced with the new one: https://github.com/acdh-oeaw/apis-core-rdf/issues/70

Right now, the classical relations between entity-entity, entity-reification-entity, is already utilizing the new logic. Vocab UI elements should do so too: https://github.com/acdh-oeaw/apis-core-rdf/issues/213

In a classical setup the old code is not used anymore **except by highlighter module.** 

Relevant code parts can be found here:
https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis_core/apis_entities/templates/apis_entities/edit_generic.html#L405
https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis_core/apis_entities/templates/apis_entities/edit_generic.html#L480
https://github.com/acdh-oeaw/apis_highlighter/blob/master/apis_highlighter/static/apis_highlighter/apis_highlighter.js#L1
https://github.com/acdh-oeaw/apis-core-rdf/blob/eb0d4bc80635d55e9ba7aa000ff614a0759c0f3a/apis_core/apis_relations/views.py#L113
https://github.com/acdh-oeaw/apis-core-rdf/blob/eb0d4bc80635d55e9ba7aa000ff614a0759c0f3a/apis_core/apis_relations/views.py#L254

These links are probably all that are necessary for this task, but there might be more other code parts too. Can't tell, as there is no documentation either. 

After this is done, rename new ajax logic functions from `ajax_2_...` simply to `ajax_...`. The `2` just acts as a differentiation to old logic.

**Comment by sennierer** [comment]
closing this as there is now a complete rewrite of the highlighter
