### ISSUE TITLE
Verify that reversions are working in apis-rdf

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core-rdf#78]
Stuff like this `@reversion.register(follow=["tempentityclass_ptr"])`, don't know how it works, never had touched it, but Matthias told me a while ago that some reversions don't work. We don't remember anymore where and in which context sadly.

Anyway, we should very that this works as intented as it helps massively in data integrity. 

So a check on all relevant data models in an example ontology is needed.

**Comment by sennierer** [comment]
related to #242

**Comment by sennierer** [comment]
closing this in favor of #242
