### ISSUE TITLE
Logout/changing user from API views not possible

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#783]
I can't seem to log out from any API views/routes, i.e. the Django REST framework menu bar. When I click on the username in the top right corner:

![Screenshot 2024-04-15 at 10-56-53 Api Root – Django REST framework](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/4ce635fc-e299-4b98-9c55-661cf0dd609d)

nothing happens. I'd expect to be presented with an option to log out equivalent to how it works on the regular, non-API menu bar.

Logging in when not already logged in, however, works fine. A click on "Log in" in the top right corner:

![Screenshot 2024-04-15 at 10-58-59 Api Root – Django REST framework](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/711a7497-5c75-4ebb-8096-1f3815a97bdf)

redirects to this login mask (at `api-auth/login/?next=/apis/api/`):

<img src="https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/b0e3c43f-639f-43d8-aa6c-a39bb7d91815" width="500"> 

Not sure if this is a problem with project-specific `urls.py` missing paths, missing redirects in API-related views, DRF JS/CSS, or other frontend settings clashing with DRF's (e.g. we have `DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5-responsive.html"` set in settings). No time to investigate right now, but wanted to report it in any case.

**Comment by b1rger** [comment]
The login and logout views [are part of the DRF](https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api). They work fine in our setup.

**Comment by koeaw** [comment]
> The login and logout views [are part of the DRF](https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api). They work fine in our setup.

Thx. "Our" as in ÖBL?

**Comment by b1rger** [comment]
> > The login and logout views [are part of the DRF](https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api). They work fine in our setup.
> 
> Thx. "Our" as in ÖBL?

No, in sicprod

**Comment by koeaw** [comment]
Hmm, this seems to have resolved itself, dunno why or how, possibly related to changes between v0.15.x and v0.17.3 (!?), but either way: both login and logout work fine now.
