### ISSUE TITLE
related entities: keep the collapsed card open on change to later page 

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#798]
currently when you click on page 2 of the related places the place card is collapsed on page load.

should be doable by checking if the url contains a pageattribute of one of the cards and open the one that is needed.

**Comment by b1rger** [comment]
Nothing is collaping in the new relations (1799ea63c3c222c075a2006495675dbdc7651315) so I'm closing this

**Comment by babslgam** [comment]
@b1rger hi, should this issue be reopened or does the frischmuth instance need an update?  
example: https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.place/update/26271

**Comment by b1rger** [comment]
> [@b1rger](https://github.com/b1rger) hi, should this issue be reopened or does the frischmuth instance need an update? example: https://frischmuth-dev.acdh-dev.oeaw.ac.at/apis/apis_ontology.place/update/26271 try paging through the expressions. (but i guess thats only an issue in the update view)

Hi! This is a rather old version of apis and I don't think it will be updated any time soon. In the newer version we don't use that collapsing card element anymore
