### ISSUE TITLE
Make Triples fully unique

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#80]
Right now it's possible to create two identical triples, like so:
```
Triple.objects.create(subj=s, obj=o, prop=p)
Triple.objects.create(subj=s, obj=o, prop=p)
```

This goes against RDF and also doesn't make sense conceputally. 

So it is needed that Triples are unqiue with regards to their three foreign keys.

**Comment by sennierer** [comment]
closing as we move to other relations
