### ISSUE TITLE
`history` module is throwing error in `enitty_base_nav.html`

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#817]
https://github.com/acdh-oeaw/apis-core-rdf/blob/fcadf02c1301a13051eb84b3114d4a441e705cd0/apis_core/apis_entities/templates/apis_entities/partials/entity_base_nav.html#L18-L24

Error: History is not registered namespace

**Comment by b1rger** [comment]
I can not reproduce this. @gythaogg I think you brought that up, can you give a bit more detail about the setup?

**Comment by gythaogg** [comment]
@b1rger
 If you don't have `"apis_core.history"` from the installed apps then I get this error from base.html in the entity detail page

![image](https://github.com/acdh-oeaw/apis-core-rdf/assets/7236469/efaecf73-d51a-48d8-8ce9-0b3455c8550c)

**Comment by b1rger** [comment]
> If you don't have "apis_core.history" from the installed apps then I get this error from base.html in the entity detail page

but only if you have added `VersionMixin` to the entity, right?

**Comment by gythaogg** [comment]
Oops. That's fair.

**Comment by b1rger** [comment]
So we can close this?

**Comment by gythaogg** [comment]
Yes! Agree with you that if the models inherit from `VersionMixin` then `apis_core.history` should be in the `INSTALLED_APPS` for APIS to behave normally.
