### ISSUE TITLE
change the default behaviour of the `merge_with` function for boolean fields

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#818]
currently booleanfields are connected via and when merged: 
https://github.com/acdh-oeaw/apis-core-rdf/blob/fcadf02c1301a13051eb84b3114d4a441e705cd0/apis_core/apis_entities/models.py#L121-L124

For boolean fields we want to keep the value in the source object

**Comment by b1rger** [comment]
Is there anything we can do to move this along? Any assistance needed?
