### ISSUE TITLE
Fix Autocomplete return format

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#82]
In my form refactoring I could not recreate the autocomplete formatting from vanilla, so that the result in the search field would be rendered as html. In my implementation the user would see `<b>result</b>` among other formatting elements included.

I hacked in a work-around that just returns plain text. But we might need the html formatting (though I don't know where it was used for anyway). 

So either re-implement this or just drop it if it's not needed anywway.

My current override is here: https://github.com/acdh-oeaw/apis-core-rdf/blob/eb0d4bc80635d55e9ba7aa000ff614a0759c0f3a/apis_core/apis_entities/autocomplete3.py#L201

**Comment by b1rger** [comment]
This was implemented in the generic app in https://github.com/acdh-oeaw/apis-core-rdf/commit/c6d326f676e039550abb8f4fda420cb9843c5aeb
