### ISSUE TITLE
Tidy up Entity Edit / Edit View

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#85]
There is still some legacy junk floating around in these views (e.g. Meta, text, labels). All of these need to checked if they are necessary or can be removed / replaced.

This is medium difficulty as some things probably need to replaced with an equivalent replacement class.

It's also medium priority as it clutters up the UI and with it hampers UX.

**Comment by b1rger** [comment]
The edit view has been replaced by one that is based on the `generic` edit view and in the process the templates where rewritting -> closing
