### ISSUE TITLE
Look into upgrading release-please workflow

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#863]
Follow-on from #862:

We are currently using `release-please-action` version `v3`, latest version is `v4.1.1`. Upgrading requires adapting the current config, see [Upgrading from v3 to v4](https://github.com/googleapis/release-please-action?tab=readme-ov-file#upgrading-from-v3-to-v4) section in their README.

Affects:
- [ ]  [`release-please.yml`](
https://github.com/acdh-oeaw/apis-core-rdf/blob/main/.github/workflows/release-please.yml) in apis-core-rdf
- [ ]  [`release-please.yml`](https://github.com/acdh-oeaw/prosnet-workflows/blob/main/.github/workflows/release-please.yml) in prosnet-workflows

(possibly more)

**Comment by b1rger** [comment]
done in 26714b119deea9a81d2b3b5d0d9fe74ffa37a140
(issues regarding other projects belong into their issue tracker)
