### ISSUE TITLE
history: drop `verbose_name` from `OriginalIDColumn`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#878]
The `verbose_name` of the `OriginalIDColumn` says "most recent" which does not really make any sense, does it? We should remove that `verbose_name`

**Comment by sennierer** [comment]
You mean as the attribute name is `most_recent` anyway? Or as the term itself doesnt make any sense.
The column links to the most recent version of the entity this history object is about. Should we maybe name it "current version"?

**Comment by b1rger** [comment]
> You mean as the attribute name is `most_recent` anyway? Or as the term itself doesnt make any sense. The column links to the most recent version of the entity this history object is about. Should we maybe name it "current version"?

I'm not sure anymore, but I guess I was referring to the term. The column lists ids of instances the version refers to, so I'd say the term "Original ID" is more correct than "most recent" (because I'd expect the most recent version of a person instance to link to a PersionVersion instance, not to a person)
