### ISSUE TITLE
In Property, rename `subj_class` to `subj_classes` and `obj_class` to `obj_classes`

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#88]
To emphasize human-readibly that there can be several. Relevant code parts: https://github.com/acdh-oeaw/apis-core-rdf/blob/eb0d4bc80635d55e9ba7aa000ff614a0759c0f3a/apis_core/apis_relations/models.py#L94

**Comment by sennierer** [comment]
closing as triples will be superseded by class based approach
