### ISSUE TITLE
fix caching module to allow for abitrary named ontology modules

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#884]
currently for determining the allowed subject and object classes for a given predicate the [caching module imports all models from `apis_ontology.models`](https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/utils/caching.py#L58). If this import fails the module cant find any allowed classes and raises an error.

**Comment by b1rger** [comment]
I am working on a PR that drops any use of `caching` alltogether
