### ISSUE TITLE
URI resolver redirects to detail-pages that no longer exist

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#885]
error: `Reverse for 'person-detail' not found. 'person-detail' is not a valid view function or pattern name.`
request: `/apis/api/metainfo/uritoobject/?uri=https://d-nb.info/gnd/119165457`

**Comment by b1rger** [comment]
This has been fixed in 24f91f1ae3e8f88a7cfbffcbc21de16e34246b97
