### ISSUE TITLE
Improve button labels on overview page

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#912]
The button labels on the [`overview/` page](https://github.com/acdh-oeaw/apis-core-rdf/blob/dce75d90793d14f2443cd3f59cd758c7b1487a1c/apis_core/generic/templates/generic/overview.html) are based on the [`contenttypes` template tag](https://github.com/acdh-oeaw/apis-core-rdf/blob/dce75d90793d14f2443cd3f59cd758c7b1487a1c/apis_core/generic/templatetags/apisgeneric.py#L37).

On my end, they look like this:
![Screenshot 2024-06-05 at 18-07-34 Title Placeholder](https://github.com/acdh-oeaw/apis-core-rdf/assets/113020169/c64b1150-5633-43d0-8119-8b571174c9e0)

Problems:
* the ones for the new `history` tables aren't super helpful because they all have the same label, "apis_ontology | Version" 
* the verbose names are inconsistently cased (I'm assuming the `history` module uses capitalisation; Django recommends lowercasing them)
* they appear to be in random order

Maybe we can come up with better labelling while also keeping the `app_label` for better differentiation.

**Comment by koeaw** [comment]
Maybe the page could be split into sections to separate the buttons for the different apps. Which would then allow to leave the app labels off the individual buttons.

**Comment by b1rger** [comment]
Related: #920
