### ISSUE TITLE
after adding a property dev server needs to be restarted before the corresponding relation forms are shown

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#914]
to reproduce:
- start a new `sample_project` with an empty sqllite db
- create a place and a person entity
- create a property that has the person as subject and the place as object
- jump back to the person -> no form to relate a place is shown
- restart the dev server -> load the person -> form to relate place is shown

Not sure this was always the case, but might have something to do with the [removing of the custom cache](https://github.com/acdh-oeaw/apis-core-rdf/pull/906)

**Comment by b1rger** [comment]
can you try with this line removed?
https://github.com/acdh-oeaw/apis-core-rdf/blob/111abd4f51cd64d9b72a85615c475a744b04edcb/apis_core/utils/helpers.py#L23
