### ISSUE TITLE
`apis_core.history` leads to broken `loaddata`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#915]
When trying to load fixtures, there is an error:
```
django.db.utils.IntegrityError: Problem installing fixture 'sample_project.json': Could not load sample_project.Person(pk=1): NOT NULL constraint failed: sample_project_versionperson.id
```

removing this method:
https://github.com/acdh-oeaw/apis-core-rdf/blob/9fd8080598bd89b00220b7406c678f04e1cca5b4/apis_core/history/models.py#L19

makes the error go away

**Comment by sennierer** [comment]
Error is coming from adding the professions m2m field to track via simple history. I realized that Profession has been removed from being tracked, but this change hasnt been migrated. Can you try to do `makemigrations` and `migrate` and then export a new fixture? I dont think it will fix the problem, but is nonetheless worth a shot before changing the m2m behavior of the history module.
