### ISSUE TITLE
Agree on black formatting

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core-rdf#93]
Since CI throws errors on invalid formatting, we will need to agree on a formatting convention in the first place, which is strictly consistent among us devs as well as the CI pipelines. 

Of course black is opioniated by default, and the best starting point would be simply not to deviate from it.

Opinions?

**Comment by b1rger** [comment]
I think this is not something you decide *once*. If someone has a proposal for a change (i.e. changing the allowed line-width to 100 characters) they can create an issue or a PR. The black settings are part of the `pyproject.toml` anyways, so every local setup should pick them up automatically

**Comment by steffres** [comment]
I agree. Where are the settings in `pyproject.toml`? In only see black's package information.

**Comment by b1rger** [comment]
> I agree. Where are the settings in `pyproject.toml`? In only see black's package information.

we are still using the defaults, so there are none

**Comment by steffres** [comment]
And CI uses only default too? Good. Then we should stick with this everyhwere.

Question is if anyone wants to deviate? I personally don't.

**Comment by koeaw** [comment]
Are you asking about using Black in general or specific rules within Black?

I thought we'd agreed on the former several months ago already, just not yet put any enforcement in place in APIS-RDF. The original idea was to use a pre-commit file, which was being tested – and may have already been included – with another (vanilla) APIS repo. I feel the GitHub actions partially solves this until... then? Or until the topic is picked up again.

Either way, AFAIK several of us have been using Black for a while based on that earlier decision, just not with any "formal" checking (shared file, GH action) in place.

**Comment by koeaw** [comment]
So maybe the ticket oughtn't be about Black specifically but about libraries/settings overall and/or where/how to run checks (on code to be merged).

**Comment by steffres** [comment]
Yeah, I rembember that too, but to my knowledge we have not agreed on local processes before check-in (manually, or git hooks).  And I didn't bother so far personally. 

But now that wrong formatting can cause CI errors, we need to conventionalize something.

**Comment by b1rger** [comment]
> Yeah, I rembember that too, but to my knowledge we have not agreed on local processes before check-in (manually, or git hooks). And I didn't bother so far personally.

Why would we agree on local processes? We have a convention, that is checked (and hopefully at some point enforced) by the CI. How you integrate that in *your* local workflow is up to you.

**Comment by steffres** [comment]
Of course. But this issue aims to adress two questions for the team:

* Any wishes to deviate from black's default? 
* Any experiences / recommendations in setup? Like pre commit hooks, etc?

**Comment by koeaw** [comment]
Moved back to backlog + removed priority field since this hasn't seen any meaningful activity in over a month and takes up space on the board.

**Comment by steffres** [comment]
obsolete as the linter forces individual devs anyway and we agreed on black's default.
