### ISSUE TITLE
search: related entity 

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#943]
Currently [this field](https://github.com/acdh-oeaw/apis-core-rdf/blob/ce5fe4cbc5b924d5fb528fb01cbbc65ad95167dc/apis_core/apis_entities/filtersets.py#L31) is used to filter the queryset using [generate_search_filter](https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/generic/helpers.py#L11)

This does not search on related entities, but rather within the queryset.

The expected behaviour is to filter the queryset and select only those entities that have a related entity (subject or object in TempTriple) that contain the searched string in any or some specific fields.

**Comment by sennierer** [comment]
we fix the filter to actually search through related entities

**Comment by sennierer** [comment]
and we add a attribute (maybe a "private" or in the Metaclass) to the models that allow to set the fields searched by filters generated by `generate_search_filter`
