### ISSUE TITLE
add visual feedback when editing relations that something happened

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#979]
currently the icon is not changed when hovering the edit icon and if you click the icon the form is loaded, but visually nothing changes.
change the icon on hover and click
scroll to form on click

**Comment by koeaw** [comment]
I noticed the edit button doesn't have its usual colour (yellow) in the relations tables, but is blue, which makes me think that that may be connected to it not appearing pressed/clicked. I.e. maybe it's integrated differently into that table than in others places and is accidentally overlayed by another element or similar.

**Comment by b1rger** [comment]
>  I.e. maybe it's integrated differently into that table than in others places and is accidentally overlayed by another element or similar.


Its a totally different edit column that does some weird ajax form loading voodoo. The whole triple table only started to inherit from `GenericTable` a one or two weeks ago

**Comment by b1rger** [comment]
The new relations (1799ea63c3c222c075a2006495675dbdc7651315) use different forms, so I'm closing this
